export interface CoreAdvantage {
  source: string;
  kind: string;
  body: string;
  levels: string[];
}

export const CORE_ADVANTAGES: Record<string, CoreAdvantage> = {
  'Linguistics': {
    source: 'CORE · P. 179',
    kind: 'MERIT',
    body: 'Every player character has perfect fluency in their birth language and (except perhaps for a charming Hungarian accent) in the dominant language of the chronicle setting. For example, a Lebanese vampire in a Mexico City-set chronicle can speak and read Arabic (or Aramaic, if they are a very old Lebanese vampire) and Spanish. Kindly Storytellers might allow vampires whose birth tongue matches that of the setting to take a second language anyway.\n\nEach dot in Linguistics allows the character to fluently speak, write, and read one additional language besides those two default languages.\n\nDon’t get hung up on the changes in language over the centuries; assume that English remains English from Anglo-Saxon times to now, for instance, for the purposes of this rule, although reading centuries-old documents or chanting in a strange dialect may impose additional Difficulty to Academics or Occult tests.',
    levels: [],
  },
  'Illiterate': {
    source: 'CORE · P. 179',
    kind: 'FLAW (●●)',
    body: 'You cannot read or write. Your Academics and Science Skills are capped at 1, and you can have no specialty in them incorporating modern knowledge.',
    levels: [],
  },
  'Repulsive': {
    source: 'CORE · P. 179',
    kind: 'FLAW (●●)',
    body: 'Not all vampires look like actors on the CW network. Some of them look even better. And some, of course, look far worse.\n\nThese modifiers only apply when you can be seen. The Storyteller rules whether these modifiers apply during Social combats on a conflict-by-conflict (or even pool-by-pool) basis.\n\nYou lose two dice from all relevant Social dice pools.',
    levels: [],
  },
  'Ugly': {
    source: 'CORE · P. 179',
    kind: 'FLAW (●)',
    body: 'You lose one die from all relevant Social dice pools.',
    levels: [],
  },
  'Beautiful': {
    source: 'CORE · P. 179',
    kind: 'MERIT (●●)',
    body: 'You add one extra die to all appropriate Social dice pools.',
    levels: [],
  },
  'Stunning': {
    source: 'CORE · P. 179',
    kind: 'MERIT (●●●●)',
    body: 'You add two extra dice to all appropriate Social dice pools, as above.',
    levels: [],
  },
  'Addiction': {
    source: 'CORE · P. 179',
    kind: 'FLAW',
    body: 'You have an addiction to a substance besides blood. Kindred with this Merit or Flaw seek blood containing that substance, drinking from users. Addiction to a specific sort of blood or refusing to drink blood containing a given substance both count as Prey Exclusion (p. 181). See p. 310 for effects of specific substances in consumed blood; these remain in effect regardless of the specific Merit or Flaw taken.\n\nRemember to specify the substance you use.',
    levels: [
      '● Addiction: Lose one dice from all pools when the last person you fed from was not on your drug, except pools for actions that will immediately obtain your drug.',
      '●● Hopeless Addiction: Lose two dice from all pools when the last person you fed from was not on your drug, except pools for actions that will immediately obtain your drug.',
    ],
  },
  'High-Functioning Addict': {
    source: 'CORE · P. 180',
    kind: 'MERIT (●)',
    body: 'You add one die to any one category of pool (specify when you choose which substance you use) when the last person you fed from was on your drug.',
    levels: [],
  },
  'Archaic': {
    source: 'CORE · P. 180',
    kind: 'FLAW',
    body: 'Only ancillae or older vampires may take either of these Flaws.',
    levels: [
      '●● Archaic: You haven’t been able to adapt to the present, or you have been long in torpor. You cannot use computers or cell phones, and your Technology rating is permanently 0. The Storyteller may penalize other dice pools involving very modern technology by one die.',
      '● Living in the Past: You haven’t grasped the modern mindset, or you just don’t want to. You have one or more seriously outdated Convictions, e.g. “The Pope’s word is law,” “Women are delicate flowers,” “Lower classes exist only to serve,” or “Burn your enemies’ baggage.” These archaic moralities maintain your Humanity but are odious to many; you lose one die from Social test dice pools involving such archaic beliefs except with vampires your age and older, who may admire your steadfast virtue.',
    ],
  },
  'Bondslave': {
    source: 'CORE · P. 180',
    kind: 'FLAW (●●)',
    body: 'You bond instantly with the taste of another’s vitae; only one drink of blood binds you, not three. Either you begin as your sire’s thrall, or consult with the Storyteller to come up with a reason that first bond has broken. Possibly your sire has been staked or in another city for more than six months?',
    levels: [],
  },
  'Bond Junkie': {
    source: 'CORE · P. 181',
    kind: 'FLAW (●)',
    body: 'The Bond feels sweeter to you once it happens. Subtract one die from your dice pools to act against a Blood Bond.',
    levels: [],
  },
  'Long Bond': {
    source: 'CORE · P. 181',
    kind: 'FLAW (●)',
    body: 'Blood Bonds on you lose their Bond strength more slowly than normal, decreasing by one for each three months without being reinforced.',
    levels: [],
  },
  'Bond Resistance': {
    source: 'CORE · P. 181',
    kind: 'MERIT (●)',
    body: 'Your Blood rebels against control. Add one die to your dice pools to resist a Blood Bond per level you take of this Merit (maximum three).',
    levels: [],
  },
  'Short Bond': {
    source: 'CORE · P. 181',
    kind: 'MERIT (●●)',
    body: 'Blood Bonds on you lose their Bond strength more rapidly than normal, decreasing at both the full moon and new moon (i.e., by two each month) if not reinforced.',
    levels: [],
  },
  'Unbondable': {
    source: 'CORE · P. 181',
    kind: 'MERIT (●●●●●)',
    body: 'You cannot be Blood Bound. If you’re ever short of cash, you can probably sell your vitae to alchemists, too.',
    levels: [],
  },
  'Vegan': {
    source: 'CORE · P. 181',
    kind: 'FLAW (●●)',
    body: 'You feed only on animal blood. You must spend two points of Willpower to drink human blood. Ventrue may not take this Flaw.',
    levels: [],
  },
  'Organovore': {
    source: 'CORE · P. 181',
    kind: 'FLAW (●●)',
    body: 'You can slake Hunger only by eating human flesh and organs, especially those rich in blood such as the heart, liver, lungs, placenta, and spleen. (Most organovore Kindred these nights make smoothies from the organs first.) Only the heart provides Resonance, if any.',
    levels: [],
  },
  'Methuselah’s Thirst': {
    source: 'CORE · P. 181',
    kind: 'FLAW (●)',
    body: 'Your Hunger can only be fully slaked by the blood of supernatural creatures. (Alchemists may be able to thicken the Blood of thin-bloods enough to sate you.) Otherwise, it constantly remains at a minimum of 1. (Or higher, depending on Blood Potency (see p. 215).',
    levels: [],
  },
  'Prey Exclusion': {
    source: 'CORE · P. 181',
    kind: 'FLAW (●)',
    body: 'You refuse to hunt a certain class of prey: drug users, women, children, policemen, innocents, a given minority or ethnic group, etc. If you feed on such prey, you gain Stains as though you had violated a chronicle Tenet. Witnessing other Kindred feeding on the object of your exclusion without interfering might also give Stains, at the Storyteller’s discretion. Ventrue with this Flaw gain an additional restriction, making their choice of vessels extremely narrow.',
    levels: [],
  },
  'Bloodhound': {
    source: 'CORE · P. 182',
    kind: 'MERIT (●)',
    body: 'You can smell the Resonance of a human’s blood without tasting it. You still need to be within olfactory range of the person. Make a Resolve + Awareness test at Difficulty 3. Increase Difficulty for perfume or distance; lower it for more intimate contact.',
    levels: [],
  },
  'Iron Gullet': {
    source: 'CORE · P. 182',
    kind: 'MERIT (●●●)',
    body: 'You can feed from cold blood, rancid blood, and fractionated plasma. None of these provide Resonances. Ventrue may not take this Merit.',
    levels: [],
  },
  'Stake Bait': {
    source: 'CORE · P. 182',
    kind: 'FLAW (●●)',
    body: 'You meet Final Death when staked through the heart, rather than entering torpor.',
    levels: [],
  },
  'Folkloric Bane': {
    source: 'CORE · P. 182',
    kind: 'FLAW (●)',
    body: 'You take Aggravated damage from a folkloric bane. Folkloric banes include:',
    levels: [
      'Ultraviolet light (damage as direct sunlight)',
      'Silver or silver-plated weapons (damage as weapon damage: simply touching a silver coin or silverware does one point of Aggravated damage)',
      'Holy water (damage as fire)',
    ],
  },
  'Folkloric Block': {
    source: 'CORE · P. 182',
    kind: 'FLAW (●)',
    body: 'When faced with a folkloric block, you must shrink away from it or spend a Willpower point to push through it. Each folkloric block you take counts as a separate one-point Flaw. Folkloric blocks include:',
    levels: [
      'Holy symbols presented by any believer (even without True Faith)',
      'Crossing visible running water (not recommended in certain cities, such as Amsterdam, Stockholm, or Venice)',
      'Crossing a threshold to a home uninvited by the owner',
      'White animal',
      'Garlic',
      'Wild roses',
      'Spilled seeds you haven’t counted',
    ],
  },
  'Stigmata': {
    source: 'CORE · P. 182',
    kind: 'FLAW (●)',
    body: 'You begin to bleed from open wounds on your hands, feet, and forehead when you reach Hunger 4. This attracts attention, leaves traces, and may penalize some dice pools at the Storyteller’s discretion.',
    levels: [],
  },
  'Eat Food': {
    source: 'CORE · P. 182',
    kind: 'MERIT (●●)',
    body: 'You can consume food without effort and might even enjoy it, though it gives no nourishment and must be expelled before resting for the day.',
    levels: [],
  },
  'Baby Teeth': {
    source: 'CORE · P. 182',
    kind: 'THIN-BLOOD FLAW',
    body: 'You never developed fangs, or the ones you’ve got are useless for feeding. You either need to cut your victims open, or you extract their blood with a syringe.',
    levels: [],
  },
  'Bestial Temper': {
    source: 'CORE · P. 182',
    kind: 'THIN-BLOOD FLAW',
    body: 'You are afflicted with the Beast equal to a full vampire. You need to test for frenzy as per the normal vampire rules.',
    levels: [],
  },
  'Branded by the Camarilla': {
    source: 'CORE · P. 182',
    kind: 'THIN-BLOOD FLAW',
    body: 'In some cities, the rulers simply hunt down and destroy thin-bloods. In other cities, the merciful Sheriff merely brands them, forcibly and painfully, to remind them of their place. (Many are then hunted down and destroyed, often on perceived slights or simple whims.) You have such an unhealing brand, and the Camarilla makes sure to keep its eyes peeled for the moment you step out of line. You can take Camarilla Contact with this Flaw; the Camarilla thrives on double-dealing of this sort.',
    levels: [],
  },
  'Clan Curse': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD FLAW',
    body: 'Remnants of your sire’s Blood still flows through your veins, carrying traces of their ancient curse. You must pick a Clan Bane to suffer from, counting your Bane Severity as 1 for this purpose. You can only pick the Brujah or Gangrel Bane if you possess the Bestial Temper Flaw, and the Tremere Bane only if you have the Catenating Blood Merit.',
    levels: [],
  },
  'Dead Flesh': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD FLAW',
    body: 'Your Blood is not strong enough to completely sustain you, and as an effect, your flesh is in a constant state of putrefaction, with a greenish tint and faint stench of rot. Any medical inspection will immediately identify you as deceased, and you receive a one-die penalty to any face-to-face Social test with a mortal. You cannot take Lifelike if you take this Flaw.',
    levels: [],
  },
  'Mortal Frailty': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD FLAW',
    body: 'You cannot Rouse the Blood to mend, instead healing as a mortal (p. 126). You cannot take Vampiric Resilience if you take this Flaw.',
    levels: [],
  },
  'Shunned by the Anarchs': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD FLAW',
    body: 'You broke an unwritten rule or thought yourself equal among equals, where some turned out more equal than others. In whichever case, the Anarchs of the regnum know of you and shun you. They’d rather throw you to the Camarilla than listen to your pleas. You cannot take Anarch Comrades if you take this Flaw.',
    levels: [],
  },
  'Vitae Dependency': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD FLAW',
    body: 'Your Blood is unable to sustain vampiric powers by itself. Unless you drink enough vampire Blood to slake one Hunger each week you lose your ability to gain and use any Disciplines (including Thin-Blood Alchemy). You regain your powers as soon as you slake at least one Hunger with vampire Blood.',
    levels: [],
  },
  'Anarch Comrades': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD MERIT',
    body: 'You have befriended the members of an Anarch coterie who tolerate your presence or even affectionately treat you as their pet. They cumulatively act as a one-dot Anarch Mawla, as long as you don’t deviate from the party line. Write them on the Relationship Map.',
    levels: [],
  },
  'Camarilla Contact': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD MERIT',
    body: 'You have caught the eye of a Camarilla recruiter who has promised you admittance and a chance at becoming a real vampire. All you need to do is keep your eyes and ears open, report on your and your coterie’s activities, and be prepared to perform any task asked of you. You have the equivalent of a one-dot Camarilla Mawla who treats you badly. Write them on the Relationship Map.',
    levels: [],
  },
  'Catenating Blood': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD MERIT',
    body: 'You can create Blood Bonds and perform the Embrace as a regular vampire. Any vampire you create this way will be a thin-blood.',
    levels: [],
  },
  'Day Drinker': {
    source: 'CORE · P. 183',
    kind: 'THIN-BLOOD MERIT',
    body: 'Sunlight halves your Health tracker (rounded up), but otherwise simply removes your vampiric abilities, including all Disciplines and Health benefits, and does no other damage. You still suffer from Hunger, however, and sooner or later you’ll need to sleep. If your health drops below your currently sustained damage levels as a result of this, you suffer the effects of Impairment or torpor (depending on type of damage) until you are clear of sunlight.',
    levels: [],
  },
  'Discipline Affinity': {
    source: 'CORE · P. 184',
    kind: 'THIN-BLOOD MERIT',
    body: 'You have an affinity for a certain Discipline, picked at character creation. You gain a dot in this Discipline and can learn and retain additional dots in it through experience expenditures, as if you were a normal vampire. (The experience point cost is the same as an out-of-clan Discipline.) Drinking blood with matching Resonance does not reward you with any extra dots in this Discipline, temporary or not.',
    levels: [],
  },
  'Lifelike': {
    source: 'CORE · P. 184',
    kind: 'THIN-BLOOD MERIT',
    body: 'You have a heartbeat, can eat food, and enjoy sexual activities like a mortal. All but the most advanced medical inspections reveal nothing out of the ordinary, assuming they happen at night.',
    levels: [],
  },
  'Thin-blood Alchemy': {
    source: 'CORE · P. 184',
    kind: 'THIN-BLOOD MERIT',
    body: 'The Duskborn change as they feed. Thin-Blood Alchemy is the mastery of this process. Whether it is spontaneous or a skill learned by comparing notes with other bloodcookers, you have gained one dot and one formula (p. 282) in Thin-blood Alchemy. You can purchase additional dots and formulae through experience as usual.',
    levels: [],
  },
  'Vampiric Resilience': {
    source: 'CORE · P. 184',
    kind: 'THIN-BLOOD MERIT',
    body: 'You suffer damage as a regular vampire, treating regular puncture and slashing wounds as Superficial damage.',
    levels: [],
  },
  'Allies': {
    source: 'CORE · P. 184',
    kind: 'BACKGROUND',
    body: 'Allies are mortals who support and help you: family, friends, or even a mortal organization that owes you some loyalty. Although Allies usually aid you willingly, without coaxing or coercion, they are not always available to offer assistance; they have their own concerns and can do only so much for the sake of your relationship. Usually, Allies appear about once per story.\n\nAllies can be almost anyone in your home city, depending on what your Storyteller will allow. You may have friends in the precinct morgue, at a tabloid newspaper or gossip blog, among high society, or at the railroad yard. Allies are generally trustworthy (though they probably don’t know that you’re a vampire, or even that vampires exist). However, nothing comes for free. If you wind up drawing favors from your friend in the Russian Mafia, he’ll probably ask you to do him a favor in kind in the future.\n\nEnemies are the opposite of Allies and are taken as Flaws.\n\nYou can use the Mortal Template rules to create Allies or Enemies when you buy them or first call on them, and you can write them down on the Relationship Map, though many groups leave this process up to the Storyteller.\n\nBuild Allies or Enemies from a budget of points based on their Effectiveness and on their Reliability. The maximum points in one Ally is six. Ally or Enemy groups appear in numbers equal to the number of player characters.\n\nAll Enemies are rated two fewer dots than their Effectiveness; a Gifted mortal Ally costs three dots as an Ally, but only provides one dot as a Flaw. Enemies all have the same Reliability: whenever the Storyteller thinks they should show up, but probably at least once per story.',
    levels: [
      '● Effectiveness: Weak mortal, likely useless in a violent or potentially violent situation.',
      '●● Effectiveness: Average mortal or a tightknit group of Weak mortals (neighborhood kids who solve mysteries, church group, NGO chapter)',
      '●●● Effectiveness: Gifted mortal or a dangerous group of Average mortals (a street gang, a celebrity entourage, a blue-collar union local)',
      '●●●● Effectiveness: Deadly mortal, a Gifted mortal with magic or other supernatural powers, or a well-armed group of Gifted mortals (a private security squad , a lawyer contingent, a Russian Mafia bratva)',
      '● Reliability: When you call on them, they appear half the time.',
      '●● Reliability: When you call on them, they appear within 1-10 hours (roll a die).',
      '●●● Reliability: When you call on them, they appear as soon as possible.',
    ],
  },
  'Enemy': {
    source: 'CORE · P. 184',
    kind: 'BACKGROUND FLAW',
    body: 'Enemies are the opposite of Allies and are taken as Flaws.\n\nBuild Allies or Enemies from a budget of points based on their Effectiveness and on their Reliability. The maximum points in one Ally is six. Ally or Enemy groups appear in numbers equal to the number of player characters.\n\nAll Enemies are rated two fewer dots than their Effectiveness; a Gifted mortal Ally costs three dots as an Ally, but only provides one dot as a Flaw. Enemies all have the same Reliability: whenever the Storyteller thinks they should show up, but probably at least once per story.',
    levels: [],
  },
  'Contacts': {
    source: 'CORE · P. 185',
    kind: 'BACKGROUND',
    body: 'You know people – human people – from many different walks of life. Contacts primarily provide you with information in their areas of expertise, and they may want to exchange favors of various kinds. For different kinds of help, use your Influence (p. 187) in the mortal world, or call on your Allies (p. 184) or Mawla (p. 192).\n\nA Contact is someone in an excellent position to get information. They might be a police dispatcher, rather than a homicide lieutenant, or a congressional staffer, rather than a senator. Information brokers, gossip columnists, underworld fixers, and reporters make excellent Contacts. You can define your Contacts when you buy this Background or as you need to introduce them in play. Whenever you create them, make sure to add them to the Relationship Map.',
    levels: [
      '● One Contact who can do or get something cheap or common for you (Resources 1). Examples: a weed dealer, a car salesman.',
      '●● One Contact who can do or get something useful for you (Resources 2). Examples: small-time gun dealer, veterinarian.',
      '●●● One Contact who can do or get something expensive or hard for you (Resources 4). Examples: security systems expert; police lieutenant in homicide, narcotics, or other useful field.',
    ],
  },
  'Fame': {
    source: 'CORE · P. 186',
    kind: 'BACKGROUND',
    body: 'Mortals know your name and eagerly seek out news of your activities. You might be a movie star, rock star, or other celebrity. Fame grants pull in mass and social media; you have more ways than most to manipulate the thoughts of the populace. You likely have ways to mask the fact that you’re never seen during the day, such as a body double.\n\nIn some circumstances, the Storyteller may allow you to use Fame in a Social test dice pool instead of another Trait, especially to get into an otherwise exclusive venue or event. “Do you know who I am?” doesn’t work everywhere, but it does work. Each level of Fame subtracts one from the Difficulty of Social tests against your fans and from many hunting tests, depending on your predation strategy – you have less trouble attracting prey.\n\nFame has its downside, of course – it’s harder for you to tail someone unobtrusively, for example, and who wants groupies hanging around the door to their haven all day tagging its location on Instagram? You should look into taking Disguise as a specialty.\n\nBy default, Fame applies among mortals, but you can also buy Fame that applies among Kindred for the same cost. Some vampires, such as Dracula or Elizabeth Bathory, might have both! Vampires may admire, or at least be more interested in, a Kindred who was famous or infamous in life: Arthur Rimbaud, Crispus Attucks, Billy the Kid, and the like.',
    levels: [
      '● A select subculture knows who you are and admires you.',
      '●● You are a local celebrity, recognized by a plurality of the city.',
      '●●● Most people in the country know your name, at least.',
      '●●●● Everybody who even vaguely cares about social trends or your field knows something about you.',
      '●●●●● Your Fame reaches mass national or even global audiences. You are a major movie star, stadium-filling rock act, or former president.',
    ],
  },
  'Infamous': {
    source: 'CORE · P. 187',
    kind: 'BACKGROUND FLAW',
    body: 'You are famous for something horrible. At the very least, the Difficulty of most reaction tests increases by the amount of the Flaw; at worst, the authorities attempt to kill or capture you whenever you appear.',
    levels: [
      '●● You are a Cleaver or serial breacher of the Masquerade, have been Blood Hunted out of another city, or have grievously offended this domain’s ruler.',
      '● You owe a big debt to bad people or have made yourself generally odious. Alternately, your spouse, lover, or close family member has Infamy ●●.',
    ],
  },
  'Dark Secret': {
    source: 'CORE · P. 187',
    kind: 'BACKGROUND FLAW (●)',
    body: 'You can also take Dark Secret, a milder version of Infamy. The Dark Secret Flaw provides one fewer point than the equivalent Infamy, as your black deeds remain unknown to all but you and perhaps one or two very motivated enemies. The one-dot version of Infamy also provides one point as a Dark Secret, because it’s easier to uncover than a truly life-threatening secret.',
    levels: [],
  },
  'Influence': {
    source: 'CORE · P. 187',
    kind: 'BACKGROUND',
    body: 'You have pull in the mortal community, whether through wealth, prestige, political office, blackmail, or supernatural manipulation. Kindred with high Influence can sway, and in rare cases even control, the politics and society of their city, especially the police and city bureaucracy.\n\nBy default, Influence applies most within one group or region of your city. Groups can be large, even diffuse: organized crime, media, religion, the police, city government, etc. Regions should be larger than neighborhoods or all but the largest individual domains: Brooklyn, the Rive Gauche, the South Side, the Ginza, etc. Your Influence applies to the city as a whole at one dot less than it does within your group or region. Using local Influence in another city in the same area, state, or province might be possible at an additional one-dot penalty, and so on. So, a vampire might be Powerful (●●●●) in Hollywood, Entrenched (●●●) everywhere in Los Angeles, merely Influential (●●) in San Diego or San Francisco, and just Well-Connected (●) in Chicago or New York.\n\nThe Storyteller may require you to use Influence in place of a Trait in some dice pools, particularly Social tests attempting to sway minor bureaucrats or the equivalent in your group. This Background helps you have an “abandoned” building demolished (or preserved), not start global wars.\n\nIf the Storyteller wants to run a game of globe-spanning masterminds, they may recalibrate Influence to potentially apply nationally (●●●●) or even globally (●●●●●).',
    levels: [
      '● Well-connected: You’re guaranteed a respectful hearing.',
      '●● Influential: People want to do you favors.',
      '●●● Entrenched: Mortal power-brokers and factions hesitate to oppose you.',
      '●●●● Powerful: Without a good reason to do otherwise, functionaries and foot soldiers obey.',
      '●●●●● Dominant: Lesser figures try to figure out what you want and do it first.',
    ],
  },
  'Despised': {
    source: 'CORE · P. 187',
    kind: 'BACKGROUND FLAW (●●)',
    body: 'One group or region of the city lives only to thwart you and your faction. Subtract two dice from dice pools attempting to convince a neutral actor to support you politically or do you a favor. The Storyteller should take any opportunity to involve your haters in the story.',
    levels: [],
  },
  'Disliked': {
    source: 'CORE · P. 187',
    kind: 'BACKGROUND FLAW (●)',
    body: 'Subtract one die from Social test dice pools involving any group in the city except your Contacts and Allies or other explicitly loyal supporters.',
    levels: [],
  },
  'Haven': {
    source: 'CORE · P. 188',
    kind: 'BACKGROUND',
    body: 'Like all Backgrounds, the Haven Background is entirely optional. A vampire with no dots in Haven has a suicide’s grave, a room in an abandoned motel, a rented office, or an apartment with windows blacked out with plastic bags. They can still remain safe and hidden by day in this relatively small and insecure haven by default. The Storyteller may allow a player character to default a somewhat better haven from another Background such as Resources, Status, or Influence. Of course, if those Backgrounds go away, so does the character’s nice haven.\n\nA character with none of those other Backgrounds, however, can still have a perfectly reasonable haven as long as they have this Background. For instance, a character might not have enough money to afford a 20-room Victorian mansion in today’s economy, but if their great-grandmother left them one that had been fully paid for, there’s no reason they can’t remain in residence as it slowly dilapidates.\n\nBase ratings in Haven abstract the haven’s size, security, and privacy. All of those factors affect the chance of spotting, penetrating, and surveilling the vampire’s actual resting place. Add +1 to the Difficulty of, or one die to dice pools resisting, such efforts for each dot of base Haven rating.\n\nKindred know their havens intimately. For each dot of base Haven rating, add one per dot to dice pools to notice danger (including awakening rolls, p. 219) while in your haven.\n\nYou can add Merits and Flaws to your Haven if you wish. They stack with the base Haven rating to produce the total dots in this Background for projects and other uses.\n\nRemember, you can make Haven a shared Background among your coterie – easily the best way to afford a Haven with lots of features.',
    levels: [
      '● Small haven, but more secure and private than the default. Examples: basement apartment, crypt, locked storeroom in a warehouse.',
      '●● Good size, security, or privacy. Examples: a single-family home or row house, wolf enclosure at the zoo, branch sewer tunnel.',
      '●●● Very large, secure, or private. Examples: a compound outside town, a bank building, a decommissioned subway station.',
    ],
  },
  'No Haven': {
    source: 'CORE · P. 188',
    kind: 'HAVEN FLAW (●)',
    body: 'You must go to some effort (at least a basic test) to find a new resting place every morning.',
    levels: [],
  },
  'Compromised': {
    source: 'CORE · P. 188',
    kind: 'HAVEN FLAW (●●)',
    body: 'Your haven has been raided once before, perhaps before it was yours. It probably appears on someone’s watchlist. Invaders or spies can add two dice to their pool to penetrate or surveil your haven. If you ever do get on the Inquisition’s radar, you should think about moving out.',
    levels: [],
  },
  'Creepy': {
    source: 'CORE · P. 188',
    kind: 'HAVEN FLAW (●)',
    body: 'Your haven looks like the den of a serial killer, which in fairness is probably exactly what it is. Unknowing neighbors might phone in a tip to the cops or just talk about the creepy place they saw. Your dice pools on Social tests to seduce or otherwise put human guests at ease are at a two-dice penalty.',
    levels: [],
  },
  'Haunted': {
    source: 'CORE · P. 188',
    kind: 'HAVEN FLAW (●)',
    body: 'Your haven has a supernatural manifestation in it that you do not control or really even understand. It might just have a ghost, but a Haunted haven could hold a dimensional portal, a cursed meteorite, or anything else you can’t get rid of. Obviously, someone who does understand the manifestation could use it to breach your haven’s security. The Storyteller defines any other effect of the haunting, imposing at least a one-die penalty to affected pools used in the haven per dot of Haunted taken as a Flaw.',
    levels: [],
  },
  'Hidden Armory': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Each dot in this Merit adds a stand of arms to your haven’s supply: one pistol and one long firearm, with ammunition. They are as secure from discovery as your resting place.',
    levels: [],
  },
  'Cell': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your haven has a dedicated, locked place to store two prisoners, with a base Difficulty to escape of 5. Each extra dot either allows you to store twice as many prisoners (up to a maximum of 32, only in very large havens) or adds +1 to the escape Difficulty. This Merit is not available in small havens.',
    levels: [],
  },
  'Watchmen': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'You have either private security or criminal thugs guarding your haven. Each dot of this Merit supplies four Average guards and one Gifted boss (see Mortal Templates, p. 185). If guards would be conspicuous here, buy this Merit cautiously.',
    levels: [],
  },
  'Laboratory': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your haven has an equipped laboratory with a dedicated industrial sink, gas jet, reinforced floor, etc. Each dot of this Merit adds one to the dice pool for rolls related to one Science or Technology specialty or to Alchemy dice pools for thin-bloods using the Fixatio method (p. 284). This Merit is not available in small havens.',
    levels: [],
  },
  'Library': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your Haven has a dedicated library on the occult, Cainite legends, city history, vampire lore, or the like. Each dot of this Merit adds one to the dice pool for research rolls for one Academics, Investigation, or Occult specialty. Small havens limit this Merit to a maximum of one dot.',
    levels: [],
  },
  'Location': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your haven nestles in one of the most fashionable or otherwise exclusive areas of the city, in the Rack, on a small island, or otherwise in a prime spot. Add two dice (or +2 to foes’ Difficulty) to bonuses on the relevant die rolls from either Chasse (p. 195) or from your base Haven rating (pick one). If neither modifier precisely maps to what you have in mind, work out with your Storyteller when you can expect a two-dice bonus to occur. For example, a Haven close to Elysium might grant a two-dice bonus to Etiquette tests in Elysium and on tests to pick up on court gossip.',
    levels: [],
  },
  'Luxury': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'High-definition flat screens, designer furniture, objets d’art, or other expensive details give you a two-dice bonus to Social tests dealing with mortal guests in your haven. If you don’t have at least three dots of Resources (●●●), your décor was gained illegally.',
    levels: [],
  },
  'Postern': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your Haven has a rear exit, secret tunnel, grating in the cellar leading into the sewers, or other unobtrusive way out. For each dot of this Merit, add one die to your dice pools to evade or escape surveillance near your haven.',
    levels: [],
  },
  'Security System': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your haven has a better-than-average security system. For each dot of this Merit, add one die to your dice pool to resist (or alert you to) unauthorized entry into your haven.',
    levels: [],
  },
  'Surgery': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your haven has one room equipped as a field surgery or better. Add two dice to relevant dice pools, generally Medicine, for tests performed in your haven. This Merit is not available in small havens.',
    levels: [],
  },
  'Warding': {
    source: 'CORE · P. 189',
    kind: 'HAVEN MERIT (●)',
    body: 'Your haven possesses some kind of magical ward barring supernatural forces. You may not be able to deactivate it, but it allows you to pass. Discuss the limits of your ward with the Storyteller. Each dot of this Merit adds one to the dice pool to resist supernatural scrying, as well as whatever other entry the Storyteller allows it to prevent. The Storyteller may require you to possess Occult 3 or better, or Blood Sorcery, to buy this Merit.',
    levels: [],
  },
  'Herd': {
    source: 'CORE · P. 189',
    kind: 'BACKGROUND',
    body: 'You have cultivated a group of vessels from whom you can feed without concern. You can use them to perform basic services, although they are neither as tightly controlled nor as loyal as Retainers. (If needed, build your Herd as a combination of Weak and Average mortals; see Mortal Templates, p. 185.) You can slake your Herd rating in Hunger each week without a roll. (This benefit can be shared among more than one vampire.) Overfeeding endangers your Herd, potentially dropping the rating as members die or flee.',
    levels: [
      '● One to three vessels with random Resonance and no Dyscrasias: You can change one victim’s Resonance once a month with a successful Manipulation + Insight test (Difficulty 4). Examples: graduate students, musical pupils, cleaver family',
      '●● Four to seven vessels, half of whom share one Resonance that you pick when you buy this Advantage. Examples: Aging devotees of the city’s fading goth or bhangra scene, fellow club scenesters, large cleaver family',
      '●●● Seven to 15 vessels, with two different Resonances that you pick each week when you feed on different Herd members. Examples: rugby team, swinger scene, dance or night school class, night shift employees',
      '●●●● 16 to 30 vessels: Pick two Resonances every week. Herd maintenance, cover ups, and recruitment take occasional roles in your chronicle. Examples: cult, large brothel, sweatshop',
      '●●●●● 31 to 60 vessels: Pick three Resonances every week. Herd maintenance and recruitment begins to brush up against the Masquerade. Examples: Large cult, large sweatshop',
    ],
  },
  'Obvious Predator': {
    source: 'CORE · P. 189',
    kind: 'BACKGROUND FLAW (●●)',
    body: 'You exude a predatory demeanor, and humans instinctively fear and mistrust you. Lose two dice from any dice pool for hunting except purely Physical expressions of stalking, chasing, and killing. Lose one die from any dice pool for any Social test intended to put humans at ease. You cannot maintain a Herd.',
    levels: [],
  },
  'Loresheets': {
    source: 'CORE · P. 190',
    kind: 'BACKGROUND',
    body: 'Buy an Advantage from a Loresheet and integrate the story of that lore into your character’s lineage and connections. Some Loresheets (especially the “Descendant of …”) require the character be of a specific clan.\n\nRemember, that just like other Advantages, each level of a Loresheet is self-contained and must be bought separately. It does not automatically convey the “lower” levels of that Loresheet.\n\nSee Loresheets on p. 382 for more.',
    levels: [],
  },
  'Mask': {
    source: 'CORE · P. 190',
    kind: 'BACKGROUND',
    body: 'As stealth predators, vampires have few weapons more potent than their pretense of humanity. The lies the Kindred live constantly shadow your stories, and no description of a lick should omit how they navigate mortal society – what they wear as a Mask. A good Mask explains the character’s nocturnal existence and offers plenty of opportunities to be alone with mortals.\n\nSome vampires switch back and forth between Masks, risking deep identity confusion and slipups, while others forge single plausible identities and strictly adhere to them for a human lifetime before they switch, adding makeup as they “age,” and faking every aspect of life to look perfectly normal on paper. Others, almost always Nosferatu or unbound vampires, forswear safety for freedom off the grid or on the streets.\n\nBy default (at no dots) a vampire either has no need of a Mask, such as those recently Embraced and still able to pass as the human they were, or has a single Mask and fake ID that can stand up to a traffic stop or similar surface scrutiny. A zero-dot mask does not pass a background check, much less a proper investigation by the authorities.\n\nIf you have a two-dot Mask, you can also buy the following Advantages for one dot each: Zeroed and Cobbler.',
    levels: [
      '● You have a good fake identity, including a credit card, bank account, credit history, birth certificate, etc., all in your Mask’s name. You can pass a state or provincial-level background check.',
      '●● Your Mask can pass a background check with the national police: FBI, Scotland Yard, or the equivalent. If you had a military or intelligence record in life, it has been classified.',
    ],
  },
  'Known Blankbody': {
    source: 'CORE · P. 190',
    kind: 'MASK FLAW (●●)',
    body: 'Your biometrics, name, history, known associates, and aliases appear in several intelligence agency databases, flagged as a potential terrorist. Any inquisitor can read between the lines and recognize you as a vampire.',
    levels: [],
  },
  'Known Corpse': {
    source: 'CORE · P. 190',
    kind: 'MASK FLAW (●)',
    body: 'People know you died recently and react with shock and horror if you appear among them. This Flaw also applies to any database lookups on your identity.',
    levels: [],
  },
  'Zeroed': {
    source: 'CORE · P. 192',
    kind: 'MASK MERIT (●)',
    body: 'Someone in high places has purged your real records. You officially don’t exist.',
    levels: [],
  },
  'Cobbler': {
    source: 'CORE · P. 192',
    kind: 'MASK MERIT (●)',
    body: 'You can make or source Masks. Making a Mask takes three days per dot and possibly exposes you online; sourcing Masks takes one day per dot, but costs something in return. How much depends on your leverage, margin on the Social test, or whatever else the Storyteller decides.',
    levels: [],
  },
  'Mawla': {
    source: 'CORE · P. 192',
    kind: 'BACKGROUND',
    body: 'This Trait represents one or a group of Kindred who looks out for you, offering guidance, information, or aid once in a while. The word comes from medieval Arabic, meaning different things from “a trusted one” to “uncle” to “source of neighborly protection” to “non-Muslim whose oath still binds them.” Western vampires brought the term back from the Crusades, and as the Ashirra and Camarilla find themselves increasingly allied in the Gehenna War, the word enjoys a resurgence in vampire society.\n\nA Mawla may act as your mentor. Such a role commonly falls to your sire, if they don’t treat you as property or ignore you.\n\nYour Mawla might trade information to mutual benefit, or even come to your aid if you have respected the relationship. A Mawla may be powerful, but their power need not be direct. Depending on the number of dots in this Background, your Mawla might be nothing more than an ancilla with a remarkable information network, or they might be a centuries-old creature with tremendous influence and supernatural power. They may offer advice, speak to the Prince or Baron on your behalf, steer other elders clear of you, or give warning when you’re walking into situations you don’t understand. Your Mawla, of course, expects reciprocity.\n\nA Mawla rating could even represent a group of like-minded vampires, such as the elders of the city’s Tremere chantry or a Trotskyite clique amongst the Anarchs in town. (The plural of Mawla is Mawali.) As a general rule, a Mawla group costs one dot more than a single Kindred of that level: a coven of elder Mawali would be a three-dot Mawla group, for example.\n\nWhoever they are, write them on your Relationship Map when you buy them.\n\nAs a general rule, Mawali provide a helpful word and occasional political pushes or cover, but they don’t fight your battles or call in valuable favors. If they must do so for their own sake to aid you, you probably lose a dot or more of this Background, after arousing their ire.\n\nCharacters can also acquire one-off Minor Boons (p. 315) from other Kindred, only during character generation. These boons cost half the points (rounded up) of the equivalent Mawla.',
    levels: [],
  },
  'Adversary': {
    source: 'CORE · P. 193',
    kind: 'BACKGROUND FLAW',
    body: 'A fellow Cainite who generally wishes you (or more likely your sire, lineage, or mentor) ill, an Adversary is the reverse Flaw of the Mawla Background. Adversaries range from one-dot elders to three-dot Princes or powerful cabals. The Storyteller uses either the Adversary’s Status or some specific other Trait when building dice pools with which to oppose the player characters, not the dots in Adversary.',
    levels: [
      '● Neonate',
      '●● Ancilla',
      '●●● Elder',
      '●●●● Primogen or Anarch Revolutionary Council member',
      '●●●●● Prince or Baron',
    ],
  },
  'Resources': {
    source: 'CORE · P. 193',
    kind: 'BACKGROUND',
    body: 'This Background describes your Resources. These benefits are not necessarily financial in nature and are rarely completely liquid, but you can often sell them to gain money. It could take weeks or even months to do so, depending on how much needs to be sold. Especially as the Second Inquisition closes down Kindred bank accounts, vampires increasingly return to holding their Resources in cash – or in gold, art, narcotics, guns, and slaves.\n\nDots of Resources provide an income for you to maintain your standard of unliving, but you must detail the source of your income and the form this Background takes. After all, it might dry up, get stolen, or otherwise vanish during the chronicle.',
    levels: [
      '● Portfolio Proletariat: You live paycheck to paycheck: apartment, car, camping equipment.',
      '●● Middle Class: Nice apartment or small house, several cars, high-end equipment',
      '●●● Rich: Great condo or nice house, luxury items, high-end equipment for several people',
      '●●●● Wealthy: Mansion, helicopter or private jet, very specialized high-end equipment',
      '●●●●● Ultra Rich: Many mansions, “anything money can buy”',
    ],
  },
  'Destitute': {
    source: 'CORE · P. 193',
    kind: 'BACKGROUND FLAW (●)',
    body: 'You have no money and no home.',
    levels: [],
  },
  'Retainer': {
    source: 'CORE · P. 194',
    kind: 'BACKGROUND',
    body: 'You have one or more loyal and steadfast servants or assistants. Retainers may be ghouls who are blood bound to you, individuals you have so Dominated over the years that they are incapable of independent action, or individuals you have so overwhelmed with your Presence that they would do anything for you.\n\nYou must always control retainers in some fashion: a salary, vitae donation, or direct mesmerism. Though typically loyal, retainers may betray you if the reward outweighs the risk or if you have treated them badly. The Storyteller can always call for a scene between you and a retainer.\n\nRetainers should act as characters, not puppets. Even ghoul retainers aren’t supermen; the most skilled servants don’t always show the highest loyalty. Everything in Vampire is a tradeoff. Storytellers can use Retainers to add flavor to the chronicle; don’t let them or their misuse damage the story.',
    levels: [
      '● Underwhelming retainer: A child, criminal lowlife, or horror nerd follows you around and does your bidding without a Blood Bond. Build them as a Weak mortal.',
      '●● A ghoul, a family servant, a human lover, or a dominated thrall: give them a backstory. Build them as an Average mortal or as a ghoul with no Advantages. For more on Ghouls, see p. 234.',
      '●●● A retainer competent enough to act independently and make lesser problems go away. They are likely a ghoul with traits equivalent to Gifted mortals, on top of their supernatural abilities.',
    ],
  },
  'Stalkers': {
    source: 'CORE · P. 194',
    kind: 'BACKGROUND FLAW (●)',
    body: 'You have a tendency to attract people who become a tad too smitten with you for your own good. A former retainer retains their memory of you and a desire to reconnect. They may be hungry, love-maddened, desperate, opportunistic, or any combination or variation. Should you get rid of them, another soon appears.',
    levels: [],
  },
  'Status': {
    source: 'CORE · P. 194',
    kind: 'BACKGROUND',
    body: 'You have something of a reputation and standing (earned or unearned) within a specified local community of Kindred, probably Camarilla or Anarch. Status among Camarilla society derives as often from your sire’s status and the respect due your particular bloodline as it does from personal achievement. High Status among Anarchs theoretically depends on the character’s contributions, but more often to their degree of connection (by Blood or coterie) to the current Baron or other ruler.\n\nStatus in one sect does not transfer to the other. By and large, Status held in another city effectively reduces by one dot; an Influential (●●●) vampire in Cartagena is only Respected (●●) in Buenos Aires.\n\nThe Storyteller may occasionally call on you to add your Status to a dice pool along with a Social Trait, especially for first meetings and court happenings. In other cases, the Storyteller may allow you to substitute your Status for a Social Trait – but other vampires may notice that you’re skating by on Status, instead of properly using the Etiquette Skill, for example.\n\nCaitiff characters begin with the Suspect Flaw and may not purchase positive Status during character creation.',
    levels: [
      '● Known: A properly introduced, welcomed neonate, seen as an up-and-comer.',
      '●● Respected: You have responsibilities now, an average ancilla.',
      '●●● Influential: You hold authority over part of the group, an average elder.',
      '●●●● Powerful: You hold office in the group, such as Sheriff, Harpy, or Scourge.',
      '●●●●● Luminary: You sit at the table of power in the group, a respected member of the Primogen',
    ],
  },
  'Shunned': {
    source: 'CORE · P. 194',
    kind: 'BACKGROUND FLAW (●●)',
    body: 'You’re completely loathed by this sect. You betrayed them, crossed a local leader, or fought them in the past. Members of this group will actively work against you if they can.',
    levels: [],
  },
  'Suspect': {
    source: 'CORE · P. 194',
    kind: 'BACKGROUND FLAW (●)',
    body: 'You’re not good with this sect at all. You weaseled out of a boon, broke an oath, or did something similar. You can try to stay out of sight and out of mind, but unless you somehow make amends, you suffer a two-dice penalty to all Social tests involving the offended faction.',
    levels: [],
  },
};
