import type { SkillKey } from '../types/character';

export interface SkillText {
  source: string;
  body: string;
  levels: string[];
  specialties: string;
}

export const CORE_SKILLS: Record<SkillKey, SkillText> = {
  athletics: {
    source: 'CORE · P. 159',
    body: 'Athletics allows you to outpace someone in pursuit, leap out of the way of an oncoming car, and climb and swim like a healthy, robust living person. A character can use Athletics in place of any Physical combat Skill in a conflict roll, but in that case, they never inflict any hits on their opponent, no matter how many successes they roll.',
    levels: [
      'You were always attentive in gym class and you still have a spring in your step.',
      'Despite being dead, you are still as fit as a mortal doing regular exercise.',
      'You are fit as a fiddle and could play professional sports. Night games, at least.',
      'With your parkour abilities, why would you need to turn into a bat?',
      'Olympic records await you; only a very few peak humans can achieve what you can. Vampires mistake your skill for Physical Disciplines.',
    ],
    specialties: 'Acrobatics, Archery, Climbing, Endurance, Jumping, Parkour, Swimming, Throwing',
  },
  brawl: {
    source: 'CORE · P. 160',
    body: 'Brawl enables characters to hit their target when they swing with fist, boot, or claw. As long as you have no weapon in hand, the attack constitutes a brawl, from elegant aikijutsu to dirty street fighting.',
    levels: [
      'You had a tough upbringing and had to fight to justify your place. You still have some moves.',
      'You received some training in hitting someone hard and accurately.',
      'You more than hold your own in a scrap.',
      'You either received Spetsnaz-quality training, or you have spent decades of afterlife in fights.',
      'You could win MMA championships even without the use of your vampiric powers.',
    ],
    specialties: 'Animals, Armed Mortals, Bar Fights, Grappling, Kindred, Sporting Combat, Unarmed Mortals, Werewolves, While in Protean Beast Form',
  },
  craft: {
    source: 'CORE · P. 160',
    body: 'Craft broadly encompasses artistry, creation of items and utilities from the beautiful to the functional, and arts and crafts from throwing pottery all the way to building and reinforcing your own haven. When you take this Skill, you get a free specialty. Unlike most Skills, you can have more specialties in Craft than you have dots.',
    levels: [
      'You are an amateur, but you know what you are doing.',
      'Your craftsmanship is admired for its functionality.',
      'Your creations can be beautiful or horrifying, but their intent always clear.',
      'Your skill is highly respected among the kine and Kindred aware of it.',
      'You are often chosen to create the focal point for parties at Elysium.',
    ],
    specialties: 'Carpentry, Carving, Design, Painting, Sculpting, Sewing, Weaponsmithing',
  },
  drive: {
    source: 'CORE · P. 160',
    body: 'Anyone (except perhaps 500-year-old vampires) can learn to drive a car. The Drive Skill connotes ability to drive fast and safely under adverse conditions or in stressful situations: to drive off-road, speed away from ambushes, win street races, and get out of chases with the Second Inquisition.',
    levels: [
      'You are a cautious driver, unlikely to make any mistakes.',
      'You can put your foot down without much fear of an accident, providing visibility is good.',
      'You have won car chases, earning a cool reputation among the Anarchs.',
      'You could be a stunt driver or the personal chauffeur of a Prince or Baron.',
      'You know cars inside and out. Few can match your skill and knowledge.',
    ],
    specialties: 'All-Terrain Vehicles, Evasion, Motorcycles, Street Racing, Stunts, Tailing, Trucks, Vintage Models',
  },
  firearms: {
    source: 'CORE · P. 160',
    body: 'Leaving a victim with holes in their throat: full-on Second Inquisition investigation. Leaving a victim with holes in their head: just another Saturday night in Baltimore. Cainites use Firearms not only for the human reasons (efficiency and thrill) but to preserve the Masquerade. This Skill comprises familiarity with small arms from holdout pistols to assault rifles. It also includes other trigger-operated weapons, such as crossbows and shoulder-fired rocket-propelled grenades. Finally, it includes cleaning, unjamming, and rapidly reloading such weapons.',
    levels: [
      'You’ve fired a gun a few times, at the range or in less-formal circumstances.',
      'You know (and know how) to keep your weapon clean, take it apart, and reassemble it.',
      'You’ve been in the shit (“seen the elephant” if you’re older than a century) and come out the other side.',
      'You can handle trick shots, called shots, running shots – really anything ending in a gunshot.',
      'You’ve been practicing since the debut of the Winchester.',
    ],
    specialties: 'Crossbows, Gun Dealing, Gunsmithing, Handloading Ammunition, Quick-Draw, Sniper, Trick Shooting',
  },
  larceny: {
    source: 'CORE · P. 163',
    body: 'This Skill entails familiarity with the tools and techniques for picking locks, planting bugs, deactivating standard burglar and car alarms, manual forgery, hot-wiring automobiles, or even safecracking, as well as countless forms of breaking and entering. Characters also use it for setting up “unbeatable” security systems or deducing how and where systems failed in a break-in. Ventrue probably call the skill “Security.” These days, most high-end security systems feature computer controls, video surveillance, or electronic alarms, so they might also involve the Technology Skill to defeat.',
    levels: [
      'You can pick a simple lock or a careless pocket.',
      'You can hotwire a car or shoplift with ease.',
      'You can identify the locations of security cameras and alarms so to best bypass them.',
      'You can defeat a keypad, re-tool an ID card, or crack a safe.',
      'You can get into – or out of – the vault of a multinational bank.',
    ],
    specialties: 'Alarms, Forgery, Grand Theft Auto, Housebreaking, Lockpicking, Pickpocket, Safecracking, Security Analysis',
  },
  melee: {
    source: 'CORE · P. 163',
    body: 'Use Melee to wield handheld weapons such as knives, chains, and baseball bats with prowess. A stake is a melee weapon, often found in the hands of would-be hunters.',
    levels: [
      'You can swing a bat or blade and mostly hit the people you intend to.',
      'Your clear competence with a weapon in hand should give attackers pause.',
      'Your skill with a melee weapon is known throughout the domain.',
      'The fools brought a gun to your knife fight.',
      'You are the domain’s weaponmaster, sought out by Kindred far and wide for your skill.',
    ],
    specialties: 'Axes, Chains, Clubs, Fencing, Disarming Blows, Garrotes, Improvised Weapons, Knives, Stakes, Swords',
  },
  stealth: {
    source: 'CORE · P. 164',
    body: 'Stealth allows a character to shadow a target, making vampires with this ability superlative hunters. They benefit from the ability to spy, sneak, and blend in with crowds when needed.',
    levels: [
      'Spotting you under the cover of darkness or in camouflage proves difficult.',
      'You can sneak by casual observers and stalk unknowing victims without raising any hackles.',
      'You evade patrolling guards, moving softly and hiding easily.',
      'Your subtle, silent passage could make you a worthy ninja – or a worthy foe for ninja.',
      'The Children of Haqim come to you for advice on stalking and hiding, if they can find you.',
    ],
    specialties: 'Ambushes, Crowds, Disguise, Hiding, Shadowing, Silent Movement, Urban, Wilderness',
  },
  survival: {
    source: 'CORE · P. 164',
    body: 'Survival conveys the ability to exist in the wild and other adverse conditions, and to return to civilization again: navigate by the stars, establish a makeshift haven, and notice werewolf signs before it’s too late. Some of its related functions apply in parks, brownfields, and other wastelands of the urban jungle.',
    levels: [
      'You know the trails and wilderness around your domain.',
      'You spend more time outdoors than inside, and you can track anyone who doesn’t possess woodcraft.',
      'You can subsist outside the city, setting traps for mortals and a shelter for yourself.',
      'You can thrive outside the city like the true predator you are.',
      'Gangrel run in packs with you – if they can keep up.',
    ],
    specialties: 'Desert, Hunting, Jungle, Tracking, Traps, Shelters, Urban Exploration, Woodlands',
  },
  animalKen: {
    source: 'CORE · P. 164',
    body: 'Animal Ken allows you to cow, pacify, and even befriend animals. This Skill allows you to predict how an animal might react in a given situation, train a domesticated creature, or even try to calm or enrage animals. Without this Skill, most creatures pointedly avoid or grow aggressive around vampires.',
    levels: [
      'Animals shy away from you but will not bolt or snap.',
      'Animals are docile around you, acting as if you aren’t there, unless you build a rapport with them.',
      'Animals treat you as if you were a warm, friendly owner, unless provoked to do otherwise.',
      'You draw animals into your orbit. Few attacking creatures maintain their aggression.',
      'You can sense an animal’s feelings and thoughts, and they can feel and act on yours.',
    ],
    specialties: 'Attack Training, Cats, Dogs, Falconry, Horses, Pacification, Rats, Snakes, Stunt Training, Wolves',
  },
  etiquette: {
    source: 'CORE · P. 164',
    body: 'Etiquette is the ability to identify and respond to the social conventions in the current scene, set new protocols, and please everyone around with your good graces. Use this Skill in both Kindred and mortal high society.',
    levels: [
      'You know how to address your local ruler without causing a faux pas.',
      'You know the rules of etiquette in each of the domain’s popular nightspots.',
      'You impress others with your command of politeness, deference, and grace.',
      'Your behavior sets trends, especially if you do something to buck the norm of etiquette.',
      'The Keeper of Elysium and the Harpies look to you to establish domain protocol.',
    ],
    specialties: 'Anarch, Camarilla, Celebrities, Corporate, Elysium, Feudal, One-Percenter, Secret Society',
  },
  insight: {
    source: 'CORE · P. 165',
    body: 'Insight grants you the ability to interpret body language, note subtle cues in expression and tone, and determine truth from lies. It also allows you to perceive and understand the motives behind another’s actions.',
    levels: [
      'You can see straight through hollow boasts.',
      'You pick up on the hidden emotion between humans and even sometimes between Kindred.',
      'You can provide psychotherapy even more effectively than someone who doesn’t want to eat their patient.',
      'You are an undead lie detector. Only the best con artists can slip one by you.',
      'People may be books of blood, but they are printed in very large type – easy to read.',
    ],
    specialties: 'Ambitions, Desires, Detect Lies, Emotions, Empathy, Interrogation, Motives, Phobias, Vices',
  },
  intimidation: {
    source: 'CORE · P. 165',
    body: 'Intimidation is the power to bully, coerce, threaten, and strongarm your way to a social victory. Vampires who rely on Intimidation do not hesitate to crush the wills – and occasionally the finger bones – of their foes.',
    levels: [
      'You can cut a scathing insult effectively.',
      'You can push your way around most humans without difficulty.',
      'Your swagger and your cruel behavior have earned you your reputation.',
      'You\'re far past mere physical threats.',
      'Even fellow Kindred may step back if you step up.',
    ],
    specialties: 'Extortion, Insults, Interrogation, Physical Coercion, Staredowns, Veiled Threats',
  },
  leadership: {
    source: 'CORE · P. 165',
    body: 'Leadership grants you the ability to lead a crowd, command a detachment, boost the morale of your supporters, or subdue a riot. A strong Prince or Baron must possess Leadership or risk losing their throne.',
    levels: [
      'You have led informal clubs before and can organize Kindred of like mind.',
      'Your voice makes itself heard in council, and even your superiors sometimes listen.',
      'You can command on the battlefield and lead your soldiers into death.',
      'You can inspire the injured and dying to action, so long as you are there to lead them.',
      'Your words fill a vampire’s heart with enough strength to make it feel alive and beating.',
    ],
    specialties: 'Command, Inspiration, Oratory, Praxis, Team Dynamics, War Pack',
  },
  performance: {
    source: 'CORE · P. 166',
    body: 'Performance covers a range of arts, from dance to poetry and comedy to storytelling. You may be an inspired performer in your own right or simply an enthusiastic student of the arts. When you take this Skill, you get a free specialty.',
    levels: [
      'You are the life of the party, but you wouldn’t take your act on stage.',
      'You have performed for others, to mixed reviews. Some love you, others hate you.',
      'You are an expert student of your chosen performing art.',
      'You perform your practiced art form stunningly, winning over even Toreador far and wide.',
      'Improvisation holds no terrors for you: every night a different audience, every night a different show.',
    ],
    specialties: 'Comedy, Dance, Drama, Drums, Guitar, Keyboards, Poetry, Public Speaking, Rap, Singing, Violin, Wind Instruments',
  },
  persuasion: {
    source: 'CORE · P. 166',
    body: 'Use Persuasion when trying to convince others that you know what’s best for them, and that one bite won’t hurt at all. Skilled persuaders can play on victims’ emotions and appeal to peers’ reason. Persuasion applies in law courts and princely courts, in boardrooms, barrooms, and bedrooms.',
    levels: [
      'You can sell to a motivated buyer.',
      'You can always swing a discount or get on the inside track of the latest gossip.',
      'You can always figure out a compromise in a given conflict.',
      'The other side starts looking for a settlement when they see you in court, human or Kindred.',
      'You may be the original silver-tongued devil.',
    ],
    specialties: 'Bargaining, Fast Talk, Interrogation, Legal Argument, Negotiation, Rhetoric',
  },
  streetwise: {
    source: 'CORE · P. 166',
    body: 'Streetwise enables characters to talk the language and negotiate the societies of the streets and the underworld. You can understand code words and slang, interpret graffiti tags, and emulate gang signs.',
    levels: [
      'You know where to score drugs and sex in your domain.',
      'You know which gangs operate in the area, including their colors and rivalries. You may have your own graffiti tag.',
      'You can tell the good shit from bad, score guns, and blend in seamlessly with street people or gangbangers.',
      'When gangsters say “I know a guy,” you’re who they know.',
      'You can hire, orchestrate, or arrange almost any criminal activity anywhere in your city.',
    ],
    specialties: 'Arms Dealing, Black Market, Bribery, Drugs, Fence Stolen Goods, Gangs, Graffiti, Personal Rep, Sex Trade, Urban Survival',
  },
  subterfuge: {
    source: 'CORE · P. 166',
    body: 'Subterfuge is the art of lying convincingly, spinning a yarn, and making good excuses for bad actions. This Skill defines your talent for intrigue, secrets, and double-dealing. Subterfuge can also used for seduction and imitating mortal behavior.',
    levels: [
      'You can tell believable, simple lies.',
      'You can hustle naive people, old and young, into giving you their things.',
      'You can operate on multiple levels, telling lies intended to be uncovered to bolster other lies.',
      'You can operate endlessly in deep cover: a perfect double agent. Perhaps you are!',
      'Nobody believes you have even a single dot in Subterfuge.',
    ],
    specialties: 'Bluff, Feign Mortality, Impeccable Lies, Innocence, The Long Con, Seduction',
  },
  academics: {
    source: 'CORE · P. 168',
    body: 'Academics reflects understanding, higher education, and ability to research fields within the humanities and the liberal arts. Historical study, for instance, is hardly “just academic” if your immortal enemies lived – and left traces – in that period. When you take this Skill, you get a free specialty. For foreign languages, use the Linguistics Merit (p. 179).',
    levels: [
      'Basic primary and secondary education; a night class at community college',
      'Basic university education or tutelage from a mediocre mentor; a four-year degree',
      'Advanced university education or dedicated personal tuition; an excellent four-year degree, a doctorate',
      'Advanced specialized study beyond university, learning into subjects few understand',
      'Refined and advanced scholarship, likely to be sought out for advice and tutelage',
    ],
    specialties: 'Architecture, English Literature, History of Art, History (specific Field or Period), Journalism, Philosophy, Research, Teaching, Theology',
  },
  awareness: {
    source: 'CORE · P. 168',
    body: 'Awareness handles your perceptions. You may spot a Child of Haqim before a strike occurs, spy a key dropped in the trash, or sense a lingering perfume.',
    levels: [
      'You have a history of knowing when something is out of place.',
      'You can spot erratic or pattern behavior in an individual.',
      'You can see through most disguises and sense concealed dangers or hidden clues.',
      'Even when you are distracted, few things are beyond your notice.',
      'Your senses are those of a wild animal.',
    ],
    specialties: 'Ambushes, Camouflage, Concealed Objects, Hearing, Instincts, Smell, Sight, Traps, Wilderness',
  },
  finance: {
    source: 'CORE · P. 168',
    body: 'Finance allows you to identify trends in the market, invest well, manipulate stock, and know when a fall is coming. It also allows you to assess – and trace – the wealth of others and broker financial deals. You can generally appraise art, property, or any other noncriminal good. Ventrue value this Skill more than some Disciplines.',
    levels: [
      'You can run a business and keep books.',
      'You can manage a corporate division or bank branch; you file impeccably plausible tax returns.',
      'Thanks to international trading, you make a fine broker on foreign stock exchanges.',
      'Investment banks follow your financial lead. You have no trouble concealing fraud.',
      'You can make money do anything, including stick to your pockets – or crash countries.',
    ],
    specialties: 'Appraisal, Banking, Black Markets, Corporate Finance, Currency Manipulation, Fine Art, Forensic Accounting, Money Laundering, Stock Market',
  },
  investigation: {
    source: 'CORE · P. 169',
    body: 'Investigation allows you to unravel cases of mundane and mysterious means, spot clues, interpret them, and trace missing persons. Vampires find this Skill especially useful when a vessel escapes.',
    levels: [
      'You love a good mystery novel and fancy yourself an amateur sleuth.',
      'You have a firm knowledge of criminology and the signature acts of local rogues.',
      'You are, or could be, a detective by trade. Nothing in a crime scene escapes you.',
      'The Sheriff comes to you when unknown parties sabotage the domain’s safety.',
      'You set riddles for others and live an enigmatic existence few can penetrate.',
    ],
    specialties: 'Criminology, Deduction, Forensics, Missing Persons, Murder, Paranormal Mysteries, Traffic Analysis',
  },
  medicine: {
    source: 'CORE · P. 169',
    body: 'Medicine allows you to fix people who are broken and diagnose causes of death or sickness in a victim. It also allows you to use medical equipment, prescribe drugs, and stanch (or encourage) rapid blood flow. Characters use Medicine to heal Aggravated Health damage in mortals (see p. 127).',
    levels: [
      'You know basic anatomy and the difference in blood flow from a vein and an artery. You can perform CPR and other first aid. You may have been a medical student in life.',
      'You can comfortably treat minor traumas and illnesses and narrow down a diagnosis. You may have been a nurse or EMT in life.',
      'Your training allows you to perform major operations and treat serious injuries. You may have been an internist, pediatrician, or general practitioner in life.',
      'You can diagnose and treat all but the rarest of illnesses. You may have been a surgeon or specialist in life.',
      'You are a noted medical expert, sought out by mortals and immortals alike.',
    ],
    specialties: 'First Aid, Haematology, Pathology, Pharmacy, Phlebotomy, Surgery, Trauma Care, Veterinary',
  },
  occult: {
    source: 'CORE · P. 170',
    body: 'Occult represents knowledge of the mystical world, extending from the rites and practices of Freemasons and Rosicrucians, all the way to Noddist scholars and real mages. You can recognize occult sigils and folk-magic practices, effective or not.',
    levels: [
      'You know the legends of Caine and the Antediluvians, and you may have read the Book of Nod.',
      'You can sift the truth from pop occult nonsense.',
      'You have firsthand experience of something inexplicable, even by Kindred standards.',
      'You could name most of the Antediluvians and even comprehend a Tremere ritual.',
      'Tremere and Children of Haqim consult with you on obscure lore.',
    ],
    specialties: 'Alchemy, Blood Magic, Faeries, Ghosts, Grimoires, Infernalism, Magi, Necromancy, Noddism, Parapsychology, Voudun, Werewolves',
  },
  politics: {
    source: 'CORE · P. 170',
    body: 'Politics covers diplomacy and bureaucracy: both human and Kindred. You can work with, and possibly put pressure on, city government and perhaps higher levels. Among Kindred, you know the inside scoop on which sects are dominant where, who is at war with whom, and where the bodies are buried. Literally.',
    levels: [
      'You follow mortal political affairs in your regnum, and you know at least what the elders reveal about Kindred politics.',
      'You can apply influence at a local level, or you know who can.',
      'You could run political campaigns or political machines, or make waves in your sect as an up-and-comer.',
      'You know the true personalities of the real movers and shakers, live and undead, in your area.',
      'You could guess at the unknown members of the Camarilla’s Inner Circle.',
    ],
    specialties: 'Anarchs, Camarilla, City Government, Clan (specific), Diplomacy, Media, National Politics, State/Provincial Politics',
  },
  science: {
    source: 'CORE · P. 171',
    body: 'Science is a broad church, covering everything from basic principles of life to the understanding of universal entropy. The laws of science govern the mortal world, and vampires who wish to rule that world study them. Levels of the Science Skill roughly match those in Academics, from “some college” to “world-famous scholar.” Also like Academics, characters with a rating in Science get a free specialty.',
    levels: [
      'You dabble in the sciences and understand the principles behind the building blocks of life.',
      'You can accurately explain the competing scientific theories of the Embrace to another vampire.',
      'You make an excellent scientific manager; you can run a laboratory, interpret scientific findings, and get up to speed on scientific research in most fields. You can repair scientific equipment.',
      'You are an expert in your field and in those allied to it.',
      'Few peers match your understanding, and others come to you for guidance.',
    ],
    specialties: 'Astronomy, Biology, Chemistry, Demolitions, Engineering, Genetics, Geology, Mathematics, Physics',
  },
  technology: {
    source: 'CORE · P. 171',
    body: 'As a Skill, Technology acts as something of a moving target; it governs the operation and understanding of “technical developments most vampires find mystifying.” In 1870, it might have governed steam engines and electricity; these nights, it governs computers and computer systems. Of course, now computers govern almost everything – including steam turbines in power plants and electrical systems in office buildings.',
    levels: [
      'You know how to upgrade a home PC and keep it protected from viruses.',
      'You can conceal your IP, operate drones, and fake a digital photograph.',
      'You can create and unleash your own viruses without fear of detection.',
      'The Prince might call you personally to manage cybersecurity for their domain.',
      'On the internet, nobody knows you’re a vampire – or that you’re there at all.',
    ],
    specialties: 'Artillery, Coding, Computer Building, Data Mining, Hacking, Networks, Phones, Surveillance Systems',
  },
};
