export interface CoreAdvantage {
  source: string;
  kind: string;
  body: string;
  levels: string[];
}

export const CORE_ADVANTAGES: Record<string, CoreAdvantage> = {
  'Linguistics': {
    source: 'CORE · P. 179',
    kind: 'MÉRITO',
    body: 'Todo personagem jogador tem fluência perfeita no idioma nativo e (exceto talvez por um charmoso sotaque húngaro) no idioma dominante do cenário da crônica. Por exemplo, um vampiro libanês em uma crônica ambientada na Cidade do México sabe falar e ler árabe (ou aramaico, se for um vampiro libanês muito antigo) e espanhol. Narradores generosos podem permitir que vampiros cujo idioma nativo coincide com o do cenário escolham um segundo idioma mesmo assim.\n\nCada dot em Linguistics permite ao personagem falar, escrever e ler com fluência um idioma adicional, além desses dois idiomas padrão.\n\nNão se prenda às mudanças do idioma ao longo dos séculos; para os fins desta regra, suponha que o inglês continua sendo inglês desde a época anglo-saxã até hoje, por exemplo, embora ler documentos centenários ou entoar um dialeto estranho possa impor Difficulty adicional a testes de Academics ou Occult.',
    levels: [],
  },
  'Illiterate': {
    source: 'CORE · P. 179',
    kind: 'DEFEITO (●●)',
    body: 'Você não sabe ler nem escrever. Suas Perícias Academics e Science ficam limitadas a 1, e você não pode ter especialização nelas que incorpore conhecimento moderno.',
    levels: [],
  },
  'Repulsive': {
    source: 'CORE · P. 179',
    kind: 'DEFEITO (●●)',
    body: 'Nem todos os vampiros parecem atores da CW. Alguns parecem ainda melhores. E alguns, claro, parecem muito piores.\n\nEstes modificadores só se aplicam quando você pode ser visto. O Narrador decide se esses modificadores valem durante combates Sociais, conflito a conflito (ou até pool a pool).\n\nVocê perde dois dados de todas as pools de dados Sociais relevantes.',
    levels: [],
  },
  'Ugly': {
    source: 'CORE · P. 179',
    kind: 'DEFEITO (●)',
    body: 'Você perde um dado de todas as pools de dados Sociais relevantes.',
    levels: [],
  },
  'Beautiful': {
    source: 'CORE · P. 179',
    kind: 'MÉRITO (●●)',
    body: 'Você adiciona um dado extra a todas as pools de dados Sociais apropriadas.',
    levels: [],
  },
  'Stunning': {
    source: 'CORE · P. 179',
    kind: 'MÉRITO (●●●●)',
    body: 'Você adiciona dois dados extras a todas as pools de dados Sociais apropriadas, como acima.',
    levels: [],
  },
  'Addiction': {
    source: 'CORE · P. 179',
    kind: 'DEFEITO',
    body: 'Você tem um vício em uma substância além do sangue. Kindred com este Merit ou Flaw procuram sangue que contenha essa substância, bebendo de usuários. Vício em um tipo específico de sangue ou recusa de beber sangue que contenha determinada substância contam ambos como Prey Exclusion (p. 181). Veja a p. 310 para os efeitos de substâncias específicas no sangue consumido; eles continuam valendo independentemente do Merit ou Flaw específico escolhido.\n\nLembre-se de especificar a substância que você usa.',
    levels: [
      '● Addiction: perca um dado de todas as pools quando a última pessoa da qual você se alimentou não estava sob a sua droga, exceto pools de ações que obtenham imediatamente a sua droga.',
      '●● Hopeless Addiction: perca dois dados de todas as pools quando a última pessoa da qual você se alimentou não estava sob a sua droga, exceto pools de ações que obtenham imediatamente a sua droga.',
    ],
  },
  'High-Functioning Addict': {
    source: 'CORE · P. 180',
    kind: 'MÉRITO (●)',
    body: 'Você adiciona um dado a uma categoria de pool (especifique ao escolher qual substância você usa) quando a última pessoa da qual você se alimentou estava sob a sua droga.',
    levels: [],
  },
  'Archaic': {
    source: 'CORE · P. 180',
    kind: 'DEFEITO',
    body: 'Apenas ancillae ou vampiros mais velhos podem escolher qualquer um destes Flaws.',
    levels: [
      '●● Archaic: você não conseguiu se adaptar ao presente, ou passou muito tempo em torpor. Você não consegue usar computadores nem celulares, e seu rating de Technology é permanentemente 0. O Narrador pode penalizar em um dado outras pools que envolvam tecnologia muito moderna.',
      '● Living in the Past: você não compreendeu a mentalidade moderna, ou simplesmente não quer. Você tem uma ou mais Convictions seriamente ultrapassadas, por exemplo “A palavra do Papa é lei”, “Mulheres são flores delicadas”, “As classes baixas existem apenas para servir” ou “Queime a bagagem dos seus inimigos”. Essas moralidades arcaicas mantêm sua Humanity, mas são odiosas para muitos; você perde um dado das pools de testes Sociais que envolvam essas crenças arcaicas, exceto com vampiros da sua idade ou mais velhos, que podem admirar sua virtude inabalável.',
    ],
  },
  'Bondslave': {
    source: 'CORE · P. 180',
    kind: 'DEFEITO (●●)',
    body: 'Você se vincula instantaneamente ao gosto da vitae de outro; basta um gole de sangue para vinculá-lo, não três. Ou você começa como thrall do seu sire, ou combine com o Narrador uma razão para esse primeiro vínculo ter se rompido. Talvez seu sire tenha sido empalado ou esteja em outra cidade há mais de seis meses?',
    levels: [],
  },
  'Bond Junkie': {
    source: 'CORE · P. 181',
    kind: 'DEFEITO (●)',
    body: 'O Bond parece mais doce para você depois que acontece. Subtraia um dado das suas pools de dados para agir contra um Blood Bond.',
    levels: [],
  },
  'Long Bond': {
    source: 'CORE · P. 181',
    kind: 'DEFEITO (●)',
    body: 'Blood Bonds sobre você perdem força mais lentamente que o normal, diminuindo em um a cada três meses sem serem reforçados.',
    levels: [],
  },
  'Bond Resistance': {
    source: 'CORE · P. 181',
    kind: 'MÉRITO (●)',
    body: 'Seu sangue se rebela contra o controle. Adicione um dado às suas pools de dados para resistir a um Blood Bond por nível que você tiver deste Merit (máximo de três).',
    levels: [],
  },
  'Short Bond': {
    source: 'CORE · P. 181',
    kind: 'MÉRITO (●●)',
    body: 'Blood Bonds sobre você perdem força mais rapidamente que o normal, diminuindo tanto na lua cheia quanto na lua nova (ou seja, em dois por mês) se não forem reforçados.',
    levels: [],
  },
  'Unbondable': {
    source: 'CORE · P. 181',
    kind: 'MÉRITO (●●●●●)',
    body: 'Você não pode sofrer Blood Bond. Se algum dia estiver sem dinheiro, provavelmente também pode vender sua vitae a alquimistas.',
    levels: [],
  },
  'Vegan': {
    source: 'CORE · P. 181',
    kind: 'DEFEITO (●●)',
    body: 'Você se alimenta apenas de sangue animal. Você deve gastar dois pontos de Willpower para beber sangue humano. Ventrue não podem escolher este Flaw.',
    levels: [],
  },
  'Organovore': {
    source: 'CORE · P. 181',
    kind: 'DEFEITO (●●)',
    body: 'Você só consegue saciar a Hunger comendo carne e órgãos humanos, especialmente os ricos em sangue, como coração, fígado, pulmões, placenta e baço. (A maioria dos Kindred organovoros hoje em dia faz primeiro um smoothie com os órgãos.) Apenas o coração fornece Resonance, se é que fornece.',
    levels: [],
  },
  'Methuselah’s Thirst': {
    source: 'CORE · P. 181',
    kind: 'DEFEITO (●)',
    body: 'Sua Hunger só pode ser totalmente saciada pelo sangue de criaturas sobrenaturais. (Alquimistas talvez consigam engrossar o Sangue de thin-bloods o bastante para saciá-lo.) Caso contrário, ela permanece constantemente em no mínimo 1. (Ou mais, dependendo da Blood Potency (veja p. 215).',
    levels: [],
  },
  'Prey Exclusion': {
    source: 'CORE · P. 181',
    kind: 'DEFEITO (●)',
    body: 'Você se recusa a caçar uma certa classe de presas: usuários de drogas, mulheres, crianças, policiais, inocentes, uma dada minoria ou grupo étnico etc. Se você se alimentar de tais presas, ganha Stains como se tivesse violado um Tenet da crônica. Presenciar outros Kindred se alimentando do objeto da sua exclusão sem interferir também pode dar Stains, a critério do Narrador. Ventrue com este Flaw ganham uma restrição adicional, tornando muito estreita a escolha de vessels.',
    levels: [],
  },
  'Bloodhound': {
    source: 'CORE · P. 182',
    kind: 'MÉRITO (●)',
    body: 'Você consegue sentir pelo cheiro a Resonance do sangue de um humano, sem prová-lo. Você ainda precisa estar ao alcance olfativo da pessoa. Faça um teste de Resolve + Awareness com Difficulty 3. Aumente a Difficulty para perfume ou distância; reduza-a para contato mais íntimo.',
    levels: [],
  },
  'Iron Gullet': {
    source: 'CORE · P. 182',
    kind: 'MÉRITO (●●●)',
    body: 'Você consegue se alimentar de sangue frio, sangue rançoso e plasma fracionado. Nenhum deles fornece Resonances. Ventrue não podem escolher este Merit.',
    levels: [],
  },
  'Stake Bait': {
    source: 'CORE · P. 182',
    kind: 'DEFEITO (●●)',
    body: 'Você encontra a Final Death ao ser empalado no coração, em vez de entrar em torpor.',
    levels: [],
  },
  'Folkloric Bane': {
    source: 'CORE · P. 182',
    kind: 'DEFEITO (●)',
    body: 'Você sofre dano Aggravated de um bane folclórico. Banes folclóricos incluem:',
    levels: [
      'Luz ultravioleta (dano como luz solar direta)',
      'Armas de prata ou banhadas a prata (dano como o da arma: simplesmente tocar uma moeda ou talheres de prata causa um ponto de dano Aggravated)',
      'Água benta (dano como fogo)',
    ],
  },
  'Folkloric Block': {
    source: 'CORE · P. 182',
    kind: 'DEFEITO (●)',
    body: 'Diante de um bloqueio folclórico, você deve recuar ou gastar um ponto de Willpower para atravessá-lo. Cada bloqueio folclórico escolhido conta como um Flaw separado de um ponto. Bloqueios folclóricos incluem:',
    levels: [
      'Símbolos sagrados apresentados por qualquer fiel (mesmo sem True Faith)',
      'Atravessar água corrente visível (não recomendado em certas cidades, como Amsterdã, Estocolmo ou Veneza)',
      'Cruzar a soleira de uma casa sem ser convidado pelo dono',
      'Animal branco',
      'Alho',
      'Rosas silvestres',
      'Sementes derramadas que você não contou',
    ],
  },
  'Stigmata': {
    source: 'CORE · P. 182',
    kind: 'DEFEITO (●)',
    body: 'Você começa a sangrar por feridas abertas nas mãos, nos pés e na testa quando chega a Hunger 4. Isso atrai atenção, deixa rastros e pode penalizar algumas pools de dados, a critério do Narrador.',
    levels: [],
  },
  'Eat Food': {
    source: 'CORE · P. 182',
    kind: 'MÉRITO (●●)',
    body: 'Você consegue consumir comida sem esforço e até pode apreciá-la, embora ela não dê nutrição alguma e precise ser expelida antes de descansar durante o dia.',
    levels: [],
  },
  'Baby Teeth': {
    source: 'CORE · P. 182',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Você nunca desenvolveu presas, ou as que tem são inúteis para se alimentar. Ou você precisa cortar suas vítimas, ou extrai o sangue delas com uma seringa.',
    levels: [],
  },
  'Bestial Temper': {
    source: 'CORE · P. 182',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Você é afligido pela Besta como um vampiro completo. Você precisa testar para Frenzy segundo as regras normais de vampiros.',
    levels: [],
  },
  'Branded by the Camarilla': {
    source: 'CORE · P. 182',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Em algumas cidades, os governantes simplesmente caçam e destroem thin-bloods. Em outras, o Sheriff misericordioso apenas os marca a ferro, à força e dolorosamente, para lembrá-los de seu lugar. (Muitos são então caçados e destruídos, muitas vezes por supostas ofensas ou simples capricho.) Você tem uma marca que não cicatriza, e a Camarilla faz questão de ficar de olho no momento em que você sair da linha. Você pode escolher Camarilla Contact com este Flaw; a Camarilla prospera em duplicidades desse tipo.',
    levels: [],
  },
  'Clan Curse': {
    source: 'CORE · P. 183',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Resquícios do Sangue do seu sire ainda correm em suas veias, trazendo vestígios de sua antiga maldição. Você deve escolher um Clan Bane para sofrer, contando sua Bane Severity como 1 para esse fim. Você só pode escolher o Bane Brujah ou Gangrel se possuir o Flaw Bestial Temper, e o Bane Tremere apenas se tiver o Merit Catenating Blood.',
    levels: [],
  },
  'Dead Flesh': {
    source: 'CORE · P. 183',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Seu Sangue não é forte o bastante para sustentá-lo completamente e, em consequência, sua carne está em constante estado de putrefação, com um tom esverdeado e um leve fedor de podridão. Qualquer inspeção médica o identificará imediatamente como morto, e você recebe uma penalidade de um dado em qualquer teste Social face a face com um mortal. Você não pode escolher Lifelike se tiver este Flaw.',
    levels: [],
  },
  'Mortal Frailty': {
    source: 'CORE · P. 183',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Você não consegue fazer Rouse no Sangue para se curar, curando-se como um mortal (p. 126). Você não pode escolher Vampiric Resilience se tiver este Flaw.',
    levels: [],
  },
  'Shunned by the Anarchs': {
    source: 'CORE · P. 183',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Você quebrou uma regra não escrita ou se julgou igual entre iguais, onde alguns se revelaram mais iguais que outros. Em qualquer dos casos, os Anarchs do regnum sabem de você e o evitam. Preferem entregá-lo à Camarilla a ouvir suas súplicas. Você não pode escolher Anarch Comrades se tiver este Flaw.',
    levels: [],
  },
  'Vitae Dependency': {
    source: 'CORE · P. 183',
    kind: 'DEFEITO THIN-BLOOD',
    body: 'Seu Sangue é incapaz de sustentar poderes vampíricos por si só. A menos que você beba Sangue de vampiro suficiente para saciar um de Hunger por semana, você perde a capacidade de ganhar e usar quaisquer Disciplinas (incluindo Thin-Blood Alchemy). Você recupera seus poderes assim que saciar pelo menos um de Hunger com Sangue de vampiro.',
    levels: [],
  },
  'Anarch Comrades': {
    source: 'CORE · P. 183',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'Você fez amizade com os membros de uma coterie Anarch que toleram sua presença ou até o tratam com carinho como seu bichinho de estimação. Juntos, eles agem como um Mawla Anarch de um dot, desde que você não se desvie da linha do grupo. Anote-os no Relationship Map.',
    levels: [],
  },
  'Camarilla Contact': {
    source: 'CORE · P. 183',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'Você chamou a atenção de um recrutador da Camarilla que lhe prometeu admissão e a chance de se tornar um vampiro de verdade. Tudo o que você precisa fazer é manter olhos e ouvidos abertos, relatar suas atividades e as da sua coterie, e estar preparado para cumprir qualquer tarefa que lhe peçam. Você tem o equivalente a um Mawla da Camarilla de um dot que o trata mal. Anote-o no Relationship Map.',
    levels: [],
  },
  'Catenating Blood': {
    source: 'CORE · P. 183',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'Você pode criar Blood Bonds e realizar o Embrace como um vampiro comum. Qualquer vampiro que você criar assim será um thin-blood.',
    levels: [],
  },
  'Day Drinker': {
    source: 'CORE · P. 183',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'A luz do sol reduz pela metade (arredondado para cima) seu Health tracker, mas, fora isso, apenas remove suas habilidades vampíricas, incluindo todas as Disciplinas e benefícios de Health, e não causa nenhum outro dano. Você ainda sofre de Hunger, porém, e cedo ou tarde precisará dormir. Se sua Health cair abaixo dos níveis de dano atualmente sustentados por causa disso, você sofre os efeitos de Impairment ou torpor (dependendo do tipo de dano) até sair da luz do sol.',
    levels: [],
  },
  'Discipline Affinity': {
    source: 'CORE · P. 184',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'Você tem afinidade com uma certa Disciplina, escolhida na criação do personagem. Você ganha um dot nessa Disciplina e pode aprender e manter dots adicionais nela por meio de gastos de experiência, como se fosse um vampiro normal. (O custo em pontos de experiência é o mesmo de uma Disciplina fora do clã.) Beber sangue com Resonance correspondente não lhe dá dots extras nessa Disciplina, temporários ou não.',
    levels: [],
  },
  'Lifelike': {
    source: 'CORE · P. 184',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'Você tem batimentos cardíacos, pode comer e desfruta de atividades sexuais como um mortal. Todas as inspeções médicas, exceto as mais avançadas, não revelam nada de extraordinário, supondo que aconteçam à noite.',
    levels: [],
  },
  'Thin-blood Alchemy': {
    source: 'CORE · P. 184',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'Os Duskborn mudam conforme se alimentam. Thin-Blood Alchemy é o domínio desse processo. Seja espontâneo ou uma habilidade aprendida comparando anotações com outros bloodcookers, você ganhou um dot e uma fórmula (p. 282) em Thin-blood Alchemy. Você pode comprar dots e fórmulas adicionais com experiência, como de costume.',
    levels: [],
  },
  'Vampiric Resilience': {
    source: 'CORE · P. 184',
    kind: 'MÉRITO THIN-BLOOD',
    body: 'Você sofre dano como um vampiro comum, tratando ferimentos perfurantes e cortantes comuns como dano Superficial.',
    levels: [],
  },
  'Allies': {
    source: 'CORE · P. 184',
    kind: 'BACKGROUND',
    body: 'Allies são mortais que apoiam e ajudam você: família, amigos ou até uma organização mortal que lhe deve alguma lealdade. Embora Allies normalmente ajudem de boa vontade, sem precisar de persuasão ou coerção, nem sempre estão disponíveis para oferecer assistência; eles têm suas próprias preocupações e só podem fazer até certo ponto em nome do relacionamento. Normalmente, Allies aparecem cerca de uma vez por história.\n\nAllies podem ser quase qualquer pessoa na sua cidade natal, dependendo do que seu Narrador permitir. Você pode ter amigos no necrotério do distrito, em um jornal sensacionalista ou blog de fofoca, na alta sociedade ou no pátio da ferrovia. Allies geralmente são confiáveis (embora provavelmente não saibam que você é um vampiro, nem mesmo que vampiros existem). No entanto, nada vem de graça. Se você acabar pedindo favores ao seu amigo da máfia russa, ele provavelmente pedirá um favor em troca no futuro.\n\nEnemies são o oposto de Allies e são adquiridos como Flaws.\n\nVocê pode usar as regras de Mortal Template para criar Allies ou Enemies quando os comprar ou quando os chamar pela primeira vez, e pode anotá-los no Relationship Map, embora muitos grupos deixem esse processo a cargo do Narrador.\n\nConstrua Allies ou Enemies a partir de um orçamento de pontos baseado em sua Effectiveness e em sua Reliability. O máximo de pontos em um único Ally é seis. Grupos de Allies ou Enemies aparecem em número igual ao de personagens jogadores.\n\nTodos os Enemies têm rating dois dots abaixo de sua Effectiveness; um Ally mortal Gifted custa três dots como Ally, mas fornece apenas um dot como Flaw. Todos os Enemies têm a mesma Reliability: sempre que o Narrador achar que devem aparecer, mas provavelmente pelo menos uma vez por história.',
    levels: [
      '● Effectiveness: mortal Weak, provavelmente inútil em uma situação violenta ou potencialmente violenta.',
      '●● Effectiveness: mortal Average ou um grupo unido de mortais Weak (crianças do bairro que resolvem mistérios, grupo de igreja, filial de ONG)',
      '●●● Effectiveness: mortal Gifted ou um grupo perigoso de mortais Average (uma gangue de rua, uma comitiva de celebridade, um sindicato de operários)',
      '●●●● Effectiveness: mortal Deadly, um mortal Gifted com magia ou outros poderes sobrenaturais, ou um grupo bem armado de mortais Gifted (uma equipe de segurança privada, um contingente de advogados, uma bratva da máfia russa)',
      '● Reliability: quando você os chama, eles aparecem metade das vezes.',
      '●● Reliability: quando você os chama, eles aparecem em 1 a 10 horas (role um dado).',
      '●●● Reliability: quando você os chama, eles aparecem o mais rápido possível.',
    ],
  },
  'Enemy': {
    source: 'CORE · P. 184',
    kind: 'DEFEITO BACKGROUND',
    body: 'Enemies são o oposto de Allies e são adquiridos como Flaws.\n\nConstrua Allies ou Enemies a partir de um orçamento de pontos baseado em sua Effectiveness e em sua Reliability. O máximo de pontos em um único Ally é seis. Grupos de Allies ou Enemies aparecem em número igual ao de personagens jogadores.\n\nTodos os Enemies têm rating dois dots abaixo de sua Effectiveness; um Ally mortal Gifted custa três dots como Ally, mas fornece apenas um dot como Flaw. Todos os Enemies têm a mesma Reliability: sempre que o Narrador achar que devem aparecer, mas provavelmente pelo menos uma vez por história.',
    levels: [],
  },
  'Contacts': {
    source: 'CORE · P. 185',
    kind: 'BACKGROUND',
    body: 'Você conhece pessoas – pessoas humanas – de muitos meios diferentes. Contacts fornecem principalmente informação em suas áreas de especialidade, e podem querer trocar favores de vários tipos. Para outros tipos de ajuda, use sua Influence (p. 187) no mundo mortal, ou chame seus Allies (p. 184) ou Mawla (p. 192).\n\nUm Contact é alguém em excelente posição para obter informação. Pode ser um despachante da polícia, em vez de um tenente da homicídios, ou um assessor do Congresso, em vez de um senador. Corretores de informação, colunistas de fofoca, fixers do submundo e repórteres são excelentes Contacts. Você pode definir seus Contacts ao comprar este Background ou conforme precisar introduzi-los em jogo. Sempre que os criar, lembre-se de adicioná-los ao Relationship Map.',
    levels: [
      '● Um Contact que consegue fazer ou obter para você algo barato ou comum (Resources 1). Exemplos: um traficante de maconha, um vendedor de carros.',
      '●● Um Contact que consegue fazer ou obter para você algo útil (Resources 2). Exemplos: traficante de armas de pequeno porte, veterinário.',
      '●●● Um Contact que consegue fazer ou obter para você algo caro ou difícil (Resources 4). Exemplos: especialista em sistemas de segurança; tenente da polícia em homicídios, narcóticos ou outro campo útil.',
    ],
  },
  'Fame': {
    source: 'CORE · P. 186',
    kind: 'BACKGROUND',
    body: 'Mortais sabem seu nome e buscam avidamente notícias das suas atividades. Você pode ser uma estrela de cinema, de rock ou outra celebridade. Fame dá influência na mídia de massa e nas redes sociais; você tem mais meios que a maioria para manipular os pensamentos da população. Você provavelmente tem meios de disfarçar o fato de nunca ser visto durante o dia, como um dublê.\n\nEm algumas circunstâncias, o Narrador pode permitir que você use Fame na pool de dados de um teste Social no lugar de outro Trait, especialmente para entrar em um local ou evento de outro modo exclusivo. “Você sabe quem eu sou?” não funciona em todo lugar, mas funciona. Cada nível de Fame subtrai um da Difficulty de testes Sociais contra seus fãs e de muitos testes de caça, dependendo da sua estratégia de predação – você tem menos dificuldade para atrair presas.\n\nFame tem seu lado negativo, claro – é mais difícil para você seguir alguém discretamente, por exemplo, e quem quer tietes na porta do seu haven o dia inteiro marcando o local no Instagram? Você deveria considerar Disguise como especialização.\n\nPor padrão, Fame se aplica entre mortais, mas você também pode comprar Fame que se aplique entre Kindred pelo mesmo custo. Alguns vampiros, como Drácula ou Elizabeth Báthory, podem ter ambas! Vampiros podem admirar, ou pelo menos se interessar mais por, um Kindred que foi famoso ou infame em vida: Arthur Rimbaud, Crispus Attucks, Billy the Kid e similares.',
    levels: [
      '● Uma subcultura seleta sabe quem você é e o admira.',
      '●● Você é uma celebridade local, reconhecida por uma boa parte da cidade.',
      '●●● A maioria das pessoas do país conhece seu nome, pelo menos.',
      '●●●● Todos que ligam, ainda que vagamente, para tendências sociais ou para a sua área sabem algo sobre você.',
      '●●●●● Sua Fame alcança audiências de massa nacionais ou até globais. Você é uma grande estrela de cinema, uma banda de rock que lota estádios ou um ex-presidente.',
    ],
  },
  'Infamous': {
    source: 'CORE · P. 187',
    kind: 'DEFEITO BACKGROUND',
    body: 'Você é famoso por algo horrível. No mínimo, a Difficulty da maioria dos testes de reação aumenta no valor do Flaw; no pior caso, as autoridades tentam matá-lo ou capturá-lo sempre que você aparece.',
    levels: [
      '●● Você é um Cleaver ou violador contumaz da Masquerade, já foi alvo de Blood Hunt e expulso de outra cidade, ou ofendeu gravemente o governante deste domínio.',
      '● Você deve uma grande dívida a gente ruim ou se tornou geralmente odioso. Alternativamente, seu cônjuge, amante ou familiar próximo tem Infamy ●●.',
    ],
  },
  'Dark Secret': {
    source: 'CORE · P. 187',
    kind: 'DEFEITO BACKGROUND (●)',
    body: 'Você também pode escolher Dark Secret, uma versão mais branda de Infamy. O Flaw Dark Secret fornece um ponto a menos que a Infamy equivalente, pois seus atos sombrios permanecem desconhecidos de todos, exceto de você e talvez de um ou dois inimigos muito motivados. A versão de um dot de Infamy também fornece um ponto como Dark Secret, porque é mais fácil de descobrir que um segredo verdadeiramente ameaçador à vida.',
    levels: [],
  },
  'Influence': {
    source: 'CORE · P. 187',
    kind: 'BACKGROUND',
    body: 'Você tem peso na comunidade mortal, seja por riqueza, prestígio, cargo político, chantagem ou manipulação sobrenatural. Kindred com Influence alta podem influenciar e, em casos raros, até controlar a política e a sociedade da sua cidade, especialmente a polícia e a burocracia municipal.\n\nPor padrão, a Influence se aplica mais dentro de um grupo ou região da sua cidade. Grupos podem ser grandes, até difusos: crime organizado, mídia, religião, polícia, governo da cidade etc. Regiões devem ser maiores que bairros ou que todos os domínios individuais, exceto os maiores: Brooklyn, a Rive Gauche, o South Side, o Ginza etc. Sua Influence se aplica à cidade como um todo com um dot a menos do que dentro do seu grupo ou região. Usar Influence local em outra cidade da mesma área, estado ou província pode ser possível com mais uma penalidade de um dot, e assim por diante. Assim, um vampiro pode ser Powerful (●●●●) em Hollywood, Entrenched (●●●) em todo Los Angeles, apenas Influential (●●) em San Diego ou San Francisco, e só Well-Connected (●) em Chicago ou Nova York.\n\nO Narrador pode exigir que você use Influence no lugar de um Trait em algumas pools de dados, particularmente testes Sociais que tentem persuadir burocratas menores ou o equivalente no seu grupo. Este Background ajuda a mandar demolir (ou preservar) um prédio “abandonado”, não a começar guerras mundiais.\n\nSe o Narrador quiser conduzir um jogo de mentores que abrangem o globo, pode recalibrar a Influence para valer potencialmente em âmbito nacional (●●●●) ou até global (●●●●●).',
    levels: [
      '● Well-connected: você tem garantia de uma audiência respeitosa.',
      '●● Influential: as pessoas querem lhe fazer favores.',
      '●●● Entrenched: poderosos e facções mortais hesitam em se opor a você.',
      '●●●● Powerful: sem uma boa razão em contrário, funcionários e soldados obedecem.',
      '●●●●● Dominant: figuras menores tentam adivinhar o que você quer e fazer antes.',
    ],
  },
  'Despised': {
    source: 'CORE · P. 187',
    kind: 'DEFEITO BACKGROUND (●●)',
    body: 'Um grupo ou região da cidade vive apenas para frustrar você e a sua facção. Subtraia dois dados das pools de dados que tentem convencer um agente neutro a apoiá-lo politicamente ou a lhe fazer um favor. O Narrador deve aproveitar qualquer oportunidade para envolver seus inimigos na história.',
    levels: [],
  },
  'Disliked': {
    source: 'CORE · P. 187',
    kind: 'DEFEITO BACKGROUND (●)',
    body: 'Subtraia um dado das pools de testes Sociais que envolvam qualquer grupo da cidade, exceto seus Contacts e Allies ou outros apoiadores explicitamente leais.',
    levels: [],
  },
  'Haven': {
    source: 'CORE · P. 188',
    kind: 'BACKGROUND',
    body: 'Como todos os Backgrounds, o Background Haven é inteiramente opcional. Um vampiro sem dots em Haven tem uma sepultura de suicida, um quarto em um motel abandonado, um escritório alugado ou um apartamento com as janelas cobertas por sacos plásticos. Por padrão, ele ainda consegue ficar seguro e escondido durante o dia nesse haven relativamente pequeno e inseguro. O Narrador pode permitir que um personagem jogador tenha por padrão um haven um pouco melhor, derivado de outro Background, como Resources, Status ou Influence. Claro que, se esses Backgrounds desaparecerem, o bom haven do personagem também desaparece.\n\nUm personagem sem nenhum desses outros Backgrounds, porém, ainda pode ter um haven perfeitamente razoável, desde que tenha este Background. Por exemplo, um personagem pode não ter dinheiro para uma mansão vitoriana de 20 cômodos na economia de hoje, mas, se a bisavó lhe deixou uma totalmente quitada, não há razão para que não possa continuar morando nela enquanto ela se deteriora lentamente.\n\nOs ratings base em Haven abstraem o tamanho, a segurança e a privacidade do haven. Todos esses fatores afetam a chance de localizar, penetrar e vigiar o verdadeiro local de descanso do vampiro. Some +1 à Difficulty desses esforços, ou um dado às pools de dados de quem resiste a eles, para cada dot do rating base de Haven.\n\nKindred conhecem seus havens intimamente. Para cada dot do rating base de Haven, some um dado por dot às pools de dados para perceber perigo (incluindo awakening rolls, p. 219) enquanto estiver no seu haven.\n\nVocê pode adicionar Merits e Flaws ao seu Haven, se quiser. Eles se somam ao rating base de Haven para produzir o total de dots neste Background para projetos e outros usos.\n\nLembre-se: você pode tornar Haven um Background compartilhado pela sua coterie – facilmente a melhor forma de pagar por um Haven com muitos recursos.',
    levels: [
      '● Haven pequeno, mas mais seguro e privado que o padrão. Exemplos: apartamento de porão, cripta, depósito trancado em um armazém.',
      '●● Bom tamanho, segurança ou privacidade. Exemplos: uma casa unifamiliar ou casa geminada, recinto dos lobos no zoológico, túnel de esgoto secundário.',
      '●●● Muito grande, seguro ou privado. Exemplos: um complexo fora da cidade, um prédio de banco, uma estação de metrô desativada.',
    ],
  },
  'No Haven': {
    source: 'CORE · P. 188',
    kind: 'DEFEITO HAVEN (●)',
    body: 'Você precisa se esforçar (pelo menos um teste básico) para encontrar um novo local de descanso toda manhã.',
    levels: [],
  },
  'Compromised': {
    source: 'CORE · P. 188',
    kind: 'DEFEITO HAVEN (●●)',
    body: 'Seu haven já foi invadido uma vez, talvez antes de ser seu. Provavelmente consta na lista de vigilância de alguém. Invasores ou espiões podem adicionar dois dados à sua pool para penetrar ou vigiar seu haven. Se algum dia você entrar no radar da Inquisição, deveria pensar em se mudar.',
    levels: [],
  },
  'Creepy': {
    source: 'CORE · P. 188',
    kind: 'DEFEITO HAVEN (●)',
    body: 'Seu haven parece o covil de um serial killer, o que, para ser justo, provavelmente é exatamente o que ele é. Vizinhos desavisados podem ligar para a polícia com uma denúncia ou simplesmente comentar sobre o lugar sinistro que viram. Suas pools de dados em testes Sociais para seduzir ou de outro modo deixar convidados humanos à vontade sofrem penalidade de dois dados.',
    levels: [],
  },
  'Haunted': {
    source: 'CORE · P. 188',
    kind: 'DEFEITO HAVEN (●)',
    body: 'Seu haven tem uma manifestação sobrenatural que você não controla nem realmente compreende. Pode ser apenas um fantasma, mas um haven Haunted pode abrigar um portal dimensional, um meteorito amaldiçoado ou qualquer outra coisa de que você não consiga se livrar. Obviamente, alguém que compreenda a manifestação poderia usá-la para violar a segurança do seu haven. O Narrador define qualquer outro efeito da assombração, impondo pelo menos uma penalidade de um dado às pools afetadas usadas no haven por dot de Haunted escolhido como Flaw.',
    levels: [],
  },
  'Hidden Armory': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Cada dot neste Merit adiciona um conjunto de armas ao suprimento do seu haven: uma pistola e uma arma de fogo longa, com munição. Elas estão tão a salvo de descoberta quanto o seu local de descanso.',
    levels: [],
  },
  'Cell': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu haven tem um local próprio e trancado para guardar dois prisioneiros, com Difficulty base de fuga 5. Cada dot extra permite guardar o dobro de prisioneiros (até um máximo de 32, apenas em havens muito grandes) ou adiciona +1 à Difficulty de fuga. Este Merit não está disponível em havens pequenos.',
    levels: [],
  },
  'Watchmen': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Você tem seguranças particulares ou capangas criminosos guardando seu haven. Cada dot deste Merit fornece quatro guardas Average e um chefe Gifted (veja Mortal Templates, p. 185). Se guardas chamariam atenção ali, compre este Merit com cautela.',
    levels: [],
  },
  'Laboratory': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu haven tem um laboratório equipado, com pia industrial dedicada, bico de gás, piso reforçado etc. Cada dot deste Merit adiciona um à pool de dados de testes relacionados a uma especialização de Science ou Technology, ou às pools de Alchemy de thin-bloods que usam o método Fixatio (p. 284). Este Merit não está disponível em havens pequenos.',
    levels: [],
  },
  'Library': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu Haven tem uma biblioteca dedicada ao oculto, a lendas Cainitas, à história da cidade, ao conhecimento vampírico ou algo do tipo. Cada dot deste Merit adiciona um à pool de dados de testes de pesquisa para uma especialização de Academics, Investigation ou Occult. Havens pequenos limitam este Merit a no máximo um dot.',
    levels: [],
  },
  'Location': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu haven se aninha em uma das áreas mais da moda ou de outro modo mais exclusivas da cidade, no Rack, em uma pequena ilha ou em outro ponto privilegiado. Some dois dados (ou +2 à Difficulty dos inimigos) aos bônus das rolagens relevantes de Chasse (p. 195) ou do seu rating base de Haven (escolha um). Se nenhum dos modificadores corresponder exatamente ao que você tem em mente, combine com seu Narrador quando você pode esperar um bônus de dois dados. Por exemplo, um Haven perto do Elysium pode conceder um bônus de dois dados em testes de Etiquette no Elysium e em testes para captar fofocas da corte.',
    levels: [],
  },
  'Luxury': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Telas planas de alta definição, mobília de grife, objets d’art ou outros detalhes caros dão um bônus de dois dados em testes Sociais com convidados mortais no seu haven. Se você não tiver pelo menos três dots de Resources (●●●), sua decoração foi obtida ilegalmente.',
    levels: [],
  },
  'Postern': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu Haven tem uma saída dos fundos, túnel secreto, grade no porão que leva ao esgoto ou outra saída discreta. Para cada dot deste Merit, adicione um dado às suas pools de dados para evitar ou escapar de vigilância perto do seu haven.',
    levels: [],
  },
  'Security System': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu haven tem um sistema de segurança melhor que a média. Para cada dot deste Merit, adicione um dado à sua pool de dados para resistir a (ou ser alertado de) entrada não autorizada no seu haven.',
    levels: [],
  },
  'Surgery': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu haven tem um cômodo equipado como cirurgia de campo ou melhor. Adicione dois dados às pools de dados relevantes, geralmente Medicine, de testes realizados no seu haven. Este Merit não está disponível em havens pequenos.',
    levels: [],
  },
  'Warding': {
    source: 'CORE · P. 189',
    kind: 'MÉRITO HAVEN (●)',
    body: 'Seu haven possui algum tipo de ward mágico que barra forças sobrenaturais. Você talvez não consiga desativá-lo, mas ele permite que você passe. Discuta os limites do seu ward com o Narrador. Cada dot deste Merit adiciona um à pool de dados para resistir a scrying sobrenatural, bem como a qualquer outra entrada que o Narrador permitir que ele impeça. O Narrador pode exigir que você possua Occult 3 ou mais, ou Blood Sorcery, para comprar este Merit.',
    levels: [],
  },
  'Herd': {
    source: 'CORE · P. 189',
    kind: 'BACKGROUND',
    body: 'Você cultivou um grupo de vessels dos quais pode se alimentar sem preocupação. Você pode usá-los para realizar serviços básicos, embora não sejam nem tão controlados nem tão leais quanto Retainers. (Se necessário, construa seu Herd como uma combinação de mortais Weak e Average; veja Mortal Templates, p. 185.) Você pode saciar um número de Hunger igual ao seu rating de Herd por semana, sem rolagem. (Este benefício pode ser dividido entre mais de um vampiro.) Alimentar-se em excesso coloca seu Herd em perigo, podendo reduzir o rating conforme membros morrem ou fogem.',
    levels: [
      '● Um a três vessels com Resonance aleatória e sem Dyscrasias: você pode mudar a Resonance de uma vítima uma vez por mês com um teste bem-sucedido de Manipulation + Insight (Difficulty 4). Exemplos: estudantes de pós-graduação, alunos de música, família cleaver',
      '●● Quatro a sete vessels, metade dos quais compartilha uma Resonance que você escolhe ao comprar esta Advantage. Exemplos: devotos envelhecidos da cena goth ou bhangra em declínio da cidade, colegas frequentadores de clubes, família cleaver grande',
      '●●● Sete a 15 vessels, com duas Resonances diferentes que você escolhe a cada semana ao se alimentar de diferentes membros do Herd. Exemplos: time de rúgbi, cena swinger, turma de dança ou de escola noturna, funcionários do turno da noite',
      '●●●● 16 a 30 vessels: escolha duas Resonances a cada semana. Manutenção do Herd, encobrimentos e recrutamento ocupam papéis ocasionais na sua crônica. Exemplos: culto, bordel grande, sweatshop',
      '●●●●● 31 a 60 vessels: escolha três Resonances a cada semana. Manutenção do Herd e recrutamento começam a roçar a Masquerade. Exemplos: culto grande, sweatshop grande',
    ],
  },
  'Obvious Predator': {
    source: 'CORE · P. 189',
    kind: 'DEFEITO BACKGROUND (●●)',
    body: 'Você exala uma postura predatória, e humanos instintivamente o temem e desconfiam de você. Perca dois dados de qualquer pool de dados de caça, exceto expressões puramente Físicas de perseguir, caçar e matar. Perca um dado de qualquer pool de dados de teste Social destinado a deixar humanos à vontade. Você não pode manter um Herd.',
    levels: [],
  },
  'Loresheets': {
    source: 'CORE · P. 190',
    kind: 'BACKGROUND',
    body: 'Compre uma Advantage de uma Loresheet e integre a história desse lore à linhagem e às conexões do seu personagem. Algumas Loresheets (especialmente as “Descendant of …”) exigem que o personagem seja de um clã específico.\n\nLembre-se de que, assim como outras Advantages, cada nível de uma Loresheet é autocontido e deve ser comprado separadamente. Ele não concede automaticamente os níveis “inferiores” daquela Loresheet.\n\nVeja Loresheets na p. 382 para mais.',
    levels: [],
  },
  'Mask': {
    source: 'CORE · P. 190',
    kind: 'BACKGROUND',
    body: 'Como predadores furtivos, os vampiros têm poucas armas mais potentes que sua pretensão de humanidade. As mentiras que os Kindred vivem acompanham constantemente suas histórias, e nenhuma descrição de um lick deveria omitir como ele circula pela sociedade mortal – o que veste como Mask. Uma boa Mask explica a existência noturna do personagem e oferece muitas oportunidades de ficar a sós com mortais.\n\nAlguns vampiros alternam entre Masks, arriscando profunda confusão de identidade e deslizes, enquanto outros forjam uma única identidade plausível e a seguem estritamente durante uma vida humana antes de trocar, acrescentando maquiagem conforme “envelhecem” e fingindo todos os aspectos da vida para parecer perfeitamente normais no papel. Outros, quase sempre Nosferatu ou vampiros sem vínculo, abrem mão da segurança pela liberdade fora do sistema ou nas ruas.\n\nPor padrão (com nenhum dot), um vampiro ou não precisa de Mask, como os recém-Abraçados que ainda passam pelo humano que eram, ou tem uma única Mask e um documento falso que resistem a uma abordagem de trânsito ou escrutínio superficial semelhante. Uma Mask de zero dots não passa por uma verificação de antecedentes, muito menos por uma investigação adequada das autoridades.\n\nSe você tem uma Mask de dois dots, também pode comprar as seguintes Advantages por um dot cada: Zeroed e Cobbler.',
    levels: [
      '● Você tem uma boa identidade falsa, incluindo cartão de crédito, conta bancária, histórico de crédito, certidão de nascimento etc., tudo em nome da sua Mask. Você passa por uma verificação de antecedentes em nível estadual ou provincial.',
      '●● Sua Mask passa por uma verificação de antecedentes da polícia nacional: FBI, Scotland Yard ou equivalente. Se você tinha registro militar ou de inteligência em vida, ele foi classificado como sigiloso.',
    ],
  },
  'Known Blankbody': {
    source: 'CORE · P. 190',
    kind: 'DEFEITO MASK (●●)',
    body: 'Sua biometria, nome, histórico, associados conhecidos e aliases aparecem em vários bancos de dados de agências de inteligência, marcados como potencial terrorista. Qualquer inquisidor consegue ler nas entrelinhas e reconhecê-lo como vampiro.',
    levels: [],
  },
  'Known Corpse': {
    source: 'CORE · P. 190',
    kind: 'DEFEITO MASK (●)',
    body: 'As pessoas sabem que você morreu recentemente e reagem com choque e horror se você aparece entre elas. Este Flaw também vale para qualquer consulta a bancos de dados sobre a sua identidade.',
    levels: [],
  },
  'Zeroed': {
    source: 'CORE · P. 192',
    kind: 'MÉRITO MASK (●)',
    body: 'Alguém em posição elevada apagou seus registros verdadeiros. Oficialmente, você não existe.',
    levels: [],
  },
  'Cobbler': {
    source: 'CORE · P. 192',
    kind: 'MÉRITO MASK (●)',
    body: 'Você pode fabricar ou obter Masks. Fabricar uma Mask leva três dias por dot e possivelmente o expõe online; obter Masks leva um dia por dot, mas custa algo em troca. Quanto depende da sua vantagem, da margem no teste Social ou de qualquer outra coisa que o Narrador decidir.',
    levels: [],
  },
  'Mawla': {
    source: 'CORE · P. 192',
    kind: 'BACKGROUND',
    body: 'Este Trait representa um Kindred, ou um grupo deles, que cuida de você, oferecendo orientação, informação ou ajuda de vez em quando. A palavra vem do árabe medieval, significando coisas diferentes, de “alguém de confiança” a “tio” e “fonte de proteção de vizinhança” até “não muçulmano cujo juramento ainda o obriga”. Vampiros ocidentais trouxeram o termo de volta das Cruzadas e, como os Ashirra e a Camarilla se veem cada vez mais aliados na Guerra da Gehenna, a palavra goza de um ressurgimento na sociedade vampírica.\n\nUm Mawla pode agir como seu mentor. Tal papel costuma caber ao seu sire, se ele não o trata como propriedade nem o ignora.\n\nSeu Mawla pode trocar informação em benefício mútuo, ou até vir em seu auxílio se você respeitou o relacionamento. Um Mawla pode ser poderoso, mas seu poder não precisa ser direto. Dependendo do número de dots neste Background, seu Mawla pode ser nada mais que uma ancilla com uma notável rede de informação, ou uma criatura de séculos com tremenda influência e poder sobrenatural. Pode oferecer conselhos, falar com o Prince ou o Baron em seu nome, manter outros elders longe de você ou avisá-lo quando você estiver caminhando para situações que não compreende. Seu Mawla, claro, espera reciprocidade.\n\nUm rating de Mawla pode até representar um grupo de vampiros de mesma mentalidade, como os elders da chantry Tremere da cidade ou uma panelinha trotskista entre os Anarchs locais. (O plural de Mawla é Mawali.) Como regra geral, um grupo de Mawla custa um dot a mais que um único Kindred daquele nível: um coven de Mawali elders seria um grupo de Mawla de três dots, por exemplo.\n\nSejam quem forem, anote-os no seu Relationship Map ao comprá-los.\n\nComo regra geral, Mawali oferecem uma palavra útil e ocasionais empurrões políticos ou cobertura, mas não lutam suas batalhas nem cobram favores valiosos. Se precisarem fazê-lo, por interesse próprio, para ajudá-lo, você provavelmente perde um dot ou mais deste Background, após atrair a ira deles.\n\nPersonagens também podem adquirir Minor Boons (p. 315) avulsos de outros Kindred, apenas durante a criação de personagem. Esses boons custam metade dos pontos (arredondado para cima) do Mawla equivalente.',
    levels: [],
  },
  'Adversary': {
    source: 'CORE · P. 193',
    kind: 'DEFEITO BACKGROUND',
    body: 'Um Cainita que, em geral, deseja mal a você (ou, mais provavelmente, ao seu sire, linhagem ou mentor), um Adversary é o Flaw inverso do Background Mawla. Adversaries vão de elders de um dot a Princes de três dots ou poderosas cabalas. O Narrador usa o Status do Adversary ou algum outro Trait específico ao montar pools de dados para opor aos personagens jogadores, não os dots em Adversary.',
    levels: [
      '● Neonate',
      '●● Ancilla',
      '●●● Elder',
      '●●●● Primogen ou membro do Conselho Revolucionário Anarch',
      '●●●●● Prince ou Baron',
    ],
  },
  'Resources': {
    source: 'CORE · P. 193',
    kind: 'BACKGROUND',
    body: 'Este Background descreve seus Resources. Esses benefícios não são necessariamente de natureza financeira e raramente são totalmente líquidos, mas você muitas vezes pode vendê-los para ganhar dinheiro. Isso pode levar semanas ou até meses, dependendo de quanto precisa ser vendido. Especialmente conforme a Segunda Inquisição fecha contas bancárias de Kindred, vampiros voltam cada vez mais a guardar seus Resources em dinheiro vivo – ou em ouro, arte, narcóticos, armas e escravos.\n\nDots de Resources fornecem uma renda para você manter seu padrão de vida não-vida, mas você deve detalhar a fonte da sua renda e a forma que este Background assume. Afinal, ela pode secar, ser roubada ou de outro modo sumir durante a crônica.',
    levels: [
      '● Portfolio Proletariat: você vive de salário em salário: apartamento, carro, equipamento de camping.',
      '●● Middle Class: apartamento bom ou casa pequena, vários carros, equipamento de ponta',
      '●●● Rich: ótimo condomínio ou boa casa, itens de luxo, equipamento de ponta para várias pessoas',
      '●●●● Wealthy: mansão, helicóptero ou jato particular, equipamento de ponta muito especializado',
      '●●●●● Ultra Rich: várias mansões, “tudo que o dinheiro pode comprar”',
    ],
  },
  'Destitute': {
    source: 'CORE · P. 193',
    kind: 'DEFEITO BACKGROUND (●)',
    body: 'Você não tem dinheiro nem lar.',
    levels: [],
  },
  'Retainer': {
    source: 'CORE · P. 194',
    kind: 'BACKGROUND',
    body: 'Você tem um ou mais servos ou assistentes leais e firmes. Retainers podem ser ghouls com Blood Bond com você, indivíduos que você Dominou ao longo dos anos a ponto de serem incapazes de ação independente, ou indivíduos que você sobrepujou com sua Presence a ponto de fazerem qualquer coisa por você.\n\nVocê deve sempre controlar os retainers de alguma forma: salário, doação de vitae ou mesmerismo direto. Embora tipicamente leais, retainers podem traí-lo se a recompensa superar o risco ou se você os tratou mal. O Narrador sempre pode pedir uma cena entre você e um retainer.\n\nRetainers devem agir como personagens, não como marionetes. Mesmo retainers ghouls não são super-homens; os servos mais habilidosos nem sempre demonstram a maior lealdade. Tudo em Vampire é uma troca. Narradores podem usar Retainers para dar sabor à crônica; não deixe que eles nem o mau uso deles prejudiquem a história.',
    levels: [
      '● Retainer decepcionante: uma criança, um criminoso de baixo escalão ou um nerd de terror o segue e cumpre suas ordens sem Blood Bond. Construa-o como mortal Weak.',
      '●● Um ghoul, um servo da família, um amante humano ou um thrall dominado: dê-lhe um histórico. Construa-o como mortal Average ou como ghoul sem Advantages. Para mais sobre Ghouls, veja a p. 234.',
      '●●● Um retainer competente o bastante para agir de forma independente e fazer problemas menores desaparecerem. Provavelmente é um ghoul com traços equivalentes aos de mortais Gifted, além de suas habilidades sobrenaturais.',
    ],
  },
  'Stalkers': {
    source: 'CORE · P. 194',
    kind: 'DEFEITO BACKGROUND (●)',
    body: 'Você tem tendência a atrair pessoas que ficam um pouquinho apaixonadas demais por você, para o seu próprio bem. Um ex-retainer mantém a memória de você e o desejo de se reconectar. Pode estar faminto, enlouquecido de amor, desesperado, oportunista ou qualquer combinação ou variação disso. Se você se livrar dele, logo aparece outro.',
    levels: [],
  },
  'Status': {
    source: 'CORE · P. 194',
    kind: 'BACKGROUND',
    body: 'Você tem certa reputação e posição (merecida ou não) dentro de uma comunidade local específica de Kindred, provavelmente Camarilla ou Anarch. O Status na sociedade da Camarilla deriva tanto do status do seu sire e do respeito devido à sua linhagem particular quanto de realização pessoal. O Status alto entre Anarchs depende, em teoria, das contribuições do personagem, mas mais frequentemente do grau de conexão dele (por Sangue ou coterie) com o Baron atual ou outro governante.\n\nStatus em uma seita não se transfere para a outra. De modo geral, o Status mantido em outra cidade se reduz efetivamente em um dot; um vampiro Influential (●●●) em Cartagena é apenas Respected (●●) em Buenos Aires.\n\nO Narrador pode ocasionalmente pedir que você some seu Status a uma pool de dados junto com um Trait Social, especialmente em primeiros encontros e acontecimentos da corte. Em outros casos, o Narrador pode permitir que você substitua um Trait Social pelo seu Status – mas outros vampiros podem notar que você está se virando só com Status, em vez de usar apropriadamente a Perícia Etiquette, por exemplo.\n\nPersonagens Caitiff começam com o Flaw Suspect e não podem comprar Status positivo durante a criação de personagem.',
    levels: [
      '● Known: um neonate devidamente apresentado e bem recebido, visto como promessa em ascensão.',
      '●● Respected: você agora tem responsabilidades, uma ancilla média.',
      '●●● Influential: você tem autoridade sobre parte do grupo, um elder médio.',
      '●●●● Powerful: você ocupa um cargo no grupo, como Sheriff, Harpy ou Scourge.',
      '●●●●● Luminary: você se senta à mesa do poder do grupo, um membro respeitado do Primogen',
    ],
  },
  'Shunned': {
    source: 'CORE · P. 194',
    kind: 'DEFEITO BACKGROUND (●●)',
    body: 'Você é completamente detestado por esta seita. Você os traiu, contrariou um líder local ou lutou contra eles no passado. Membros deste grupo trabalharão ativamente contra você se puderem.',
    levels: [],
  },
  'Suspect': {
    source: 'CORE · P. 194',
    kind: 'DEFEITO BACKGROUND (●)',
    body: 'Você não é bem visto de forma alguma por esta seita. Você escapou de um boon, quebrou um juramento ou fez algo semelhante. Você pode tentar ficar fora de vista e da memória, mas, a menos que de algum modo faça as pazes, sofre uma penalidade de dois dados em todos os testes Sociais que envolvam a facção ofendida.',
    levels: [],
  },
};
